### PR TITLE
Autotilesets for Tileset Variants

### PR DESCRIPTION
**Pull request by Eauix**
This is meant to be a complement for #3082. As the game will soon support multiple autotilesets per tile, this request is focused on adding new autotilesets for many tileset variants in the game that couldn't have autotilesets before due to them sharing the same tile IDs with other tilesets.

### New Autotilesets For Worldmaps:

- Sharing tiles with Snow:
	- Snow Layer
	- Snow Cliff

- Sharing tiles with Ice Cave:
	- Ice Cave Cliff
	
- Sharing tiles with Ice Cave Ceiling:
	- Ice Holes

- Sharing tiles with Forest:
	- Forest Cliff

- Sharing tiles with Corrupted Forest:
	- Corrupted Forest Cliff
	- Corrupted Forest Transition

- Sharing tiles with Forest Underground
	- Forest Underground Cliff

- Sharing tiles with Corrupted Forest Underground
	- Corrupted Forest Underground Cliff

- Autotiles for Vertical and Horizontal Water Waves

### New Autotilesets For Levels:
- Sharing tiles with Snow:
	- Snow with Ice Floor
	- Snow Holes

- Sharing tiles with Snow Underground:
	- Snow Underground Holes

- Sharing tiles with Forest:
	- Forest with Earth Floor
	- Forest Holes

- Sharing tiles with Forest Underground:
	- Forest Underground Holes

- Sharing tiles with Corrupted Forest
	- Corrupted Forest with Earth Floor
	- Corrupted Forest Holes

- Sharing tiles with Corrupted Forest Underground
	- Corrupted Forest Underground Holes

- Autotiles for Vertical and Horizontal Rock Blocks

- Autotiles for Ice Castle and Forest Castle

- Autotiles for Vertical and Horizontal Chains, with attached and loose ends

### Tweaks and Extra Features:

- Fixes the worldmap snow tileset being only eraseable from the corners
- Added a black tile near the worldmap ice hole tileset in the tilegroup
- Improvements to some autotile comments
- Added a 2x2 rock block in the tilegroup for easier building
- 29 new tiles needed for the snow with ice floor autotileset
- 12 new tiles needed for the castle autotilesets
- 8 brand new mini-chain tiles (with autotiles included)
- Fixes the electrified water surface not being swimmable
- 3 new tiles as vertical "sign rods" for decoration

Todo List:

- [x] Add all the new worldmap autotilesets
- [x] Add the new level autotilesets

### CODE REVIEW

**Comment by Eauix** [comment]
The ice floor special tiles still need some tweaks, other than this, it's pretty much done

**Review by Frostwithasideofsalt — APPROVED** [review]

**Review by tylerandari13 — APPROVED** [review]

**Comment by Eauix** [comment]
The autotiles overhaul is ready for review and testing

**Review by Frostwithasideofsalt — APPROVED** [review]
aaaaaah i tested it again and it works ! ! ! !

**Comment by Alasdairbugs** [comment]
Tested, this works, however I would prefer if the autotile started at 1 and not 0. 0 is at the other end of the keyboard. just a small detail.

**Pull request merged**
