### PR TITLE
Fix branch name display on download.supertux.org

### PR DESCRIPTION
**Pull request by tobbi**
Let's see if this works.

### CODE REVIEW

**Comment by tobbi** [comment]
Okay. This worked! 👍

**Comment by tobbi** [comment]
The echo was only because I suspected the code wasn't run due to whatever thing. But now that it works, let's just keep the echo there. I mean, it might make the CI builds run 0.0000000000000001% slower, but that's a risk I'm willing to take:
https://stackoverflow.com/questions/72564680/am-i-correct-in-assuming-that-echo-and-cat-are-too-fast-for-the-time-comma

**Review by Zwatotem — APPROVED** [review]
I have no idea, what this fixes. Is it just to debug something else?
But whatever it is – sure, go ahead!

**Review by mrkubax10 — APPROVED** [review]

**Comment by Vankata453** [comment]
In my opinion it would be better if we don't show non-`master` builds at all - I would imagine the average player wouldn't care what branch they are downloading a Nightly from.

**Comment by tobbi** [comment]
> I have no idea, what this fixes. Is it just to debug something else? But whatever it is – sure, go ahead!

Fixes the empty branch cells in https://download.supertux.org/

**Comment by tobbi** [comment]
I feel like having the ability to download feature branches to test them quickly could be beneficial for testers.

**Comment by MatusGuy** [comment]
They can do this through github actions pages. Not through download.supertux.org

**Comment by tobbi** [comment]
download.supertux.org contains untested changes anyway. It's not like commits on master could be considered "stable" enough to be tested by end users.

**Comment by tobbi** [comment]
What would be great is if we could have a branch selector on download.supertux.org that defaults to "master".

**Comment by MatusGuy** [comment]
You're missing the point. Commits on pull requests are much much less stable than master commits. Most master commits consist of merging pull requests that have been reviewed and tested

**Comment by MatusGuy** [comment]
Or we can have a branch selector, that also works, do you want to implement that?

**Comment by tobbi** [comment]
I don't have access to the server hosting download.supertux.org, only @maths22 could do that.

**Review by weluvgoatz — APPROVED** [review]

**Pull request merged**
