### PR TITLE
Disable the update checker by default and add option to disable networking

### PR DESCRIPTION
**Pull request by Semphriss**
This avoids some privacy concerns linked to pinging an external server each time the game is open.

It also allows the user to decide whether the game should connect to the internet at all.

### CODE REVIEW

**Comment by mrkubax10** [comment]
It seems like when networking is disabled the "Checking for new releases" message doesn't disappear

Zrzut ekranu z 2023-01-29 14-17-51

**Comment by Zwatotem** [comment]
If we're pushing this, first time opening the game should greet you with a question if you want updates to be checked automatically. The feature was made mainly to promote new version updates to those who won't ever take action themselves. If it's disabled by default; it could as well not be there.

**Comment by Vankata453** [comment]
This PR should be ready for review.

**Review by Frostwithasideofsalt — APPROVED** [review]

**Review by weluvgoatz — APPROVED** [review]

**Review by tobbi — APPROVED** [review]
Gave this a cursory look. Looking good so far.

**Pull request merged**
