### PR TITLE
Fix issue #1523 with option 1

### PR DESCRIPTION
**Pull request by omeritzics**

### CODE REVIEW

**Comment by tobbi** [comment]
If we return before the switch, SuperTux-Medium.ttf will be returned every time. Can you check what auto-detect returns on your system, e.g. by adding a ` log_debug << "some string here " << some_variable << std::endl;`?

**Comment by omeritzics** [comment]
Hello, how to check it?

**Comment by Zwatotem** [comment]
> If we return before the switch, SuperTux-Medium.ttf will be returned every time. Can you check what auto-detect returns on your system, e.g. by adding a ` log_debug << "some string here " << some_variable << std::endl;`?

In this case _some_variable_ should be `std::locale().name()`. This string is supplied by system, so I'm concerned it can be different system to system, even for the same locale, so for exaple it can be "he" on some systems, and "he_IL" on others.

So the thing, that should be passed to this function, should be `std::locale().name()` in case auto locale is set.  
I recommend changing all the `==` comparisons in this font seletion code with `string::find()` for broader selection of possible values.

**Comment by omeritzics** [comment]
Hello, this pull request moved to [here](https://github.com/SuperTux/supertux/pull/1525).

**Pull request closed without merging**
