### PR TITLE
Bonus island 1,2 level tweaks

### PR DESCRIPTION
**Pull request by Hume2**
- Extended height to 36 tiles.
- Tileset fixes
- Tile backgrounds for icy levels

### CODE REVIEW

**Comment by tobbi** [comment]
Hey, some feedback you might want to consider (I'll add more once I have taken a look at the levels in order):

**Comment by sydneyjd** [comment]
Yes @Hume2, can you do what tobbi has shown up there?

**Comment by tobbi** [comment]
Is the secret area in torfi-level3 still reachable, by the way?

**Comment by MarkkusCraft123** [comment]
Is there still levels to do, I would love to work on these levels.

**Comment by tobbi** [comment]
You can always take a look at the levels and fix what looks weird.

**Pull request merged**
