### PR TITLE
Tux improvements

### PR DESCRIPTION
**Pull request by Alzter**
[ci skip] [skip ci] Adjustments/Additions to Tux's animation set.

Changes:
• Big and Small Tux's standing has been cleaned up a little.
• Big and Small Tux's idle animations have been fixed to not change position slightly.
• Big Tux's walking animation has been redone as an 8 frame animation, matching small Tux's.
• Big and Small Tux have completely new ladder animations.
• Big Tux has new work in progress sliding and swimming animations to be used in future.
• Fire and Ice Tux now have separate sprites for their hats like Earth, Air and Santa Tux, however they don't work in game yet (please fix).
• Ice Tux's hat has received some clean-ups. Fire Tux's hat may possibly receive the same treatment down the track.
• Statue Tux entirely redone.

### CODE REVIEW

**Comment by tobbi** [comment]
As this is WIP, I won't be merging for 0.6.0

**Comment by Alzter** [comment]
Tux now has the hats for his climbing animation making it complete. Can this be integrated in future? There's still a couple bugs with this but they're on the code side of things which I can't fix.

**Comment by Alzter** [comment]
Fixed. Ice and Fire Tux's buttjump is now implemented. Please merge my patch.

**Comment by HybridDog** [comment]
Tux now does not have a firepower hat:
I hope you can see the webp image

**Comment by Alzter** [comment]
His fire and ice hat sprites are now organized like the earth/air/santa hats, although they need to be coded to work way.

**Comment by HybridDog** [comment]
There are three places where the hat presence is tested. A has_hat() method could be added.
https://github.com/SuperTux/supertux/blob/ff4eff8b10b5ad80962689d427555a8b497d95f5/src/object/player.cpp#L349-L351
https://github.com/SuperTux/supertux/blob/ff4eff8b10b5ad80962689d427555a8b497d95f5/src/object/player.cpp#L1272-L1280
https://github.com/SuperTux/supertux/blob/ff4eff8b10b5ad80962689d427555a8b497d95f5/src/object/player.cpp#L1320-L1324

**Pull request merged**
