### PR TITLE
Remove Boost dependency

### PR DESCRIPTION
**Pull request by SuicSoft**
This will remove the Boost dependency of SuperTux. I have done play testing of this branch and there seems to be no bugs.

Uses some C++11.

Tested on Ubuntu 16.04.

### CODE REVIEW

**Comment by Grumbel** [comment]
The format() patch looks completely messed up, lots of boost format strings are left in that printf() won't accept and worse, lots of passing std::string into format() and then into printf() which doesn't work either, that only accepts standard C types.

For getting rid of boost in is_christmas() use std::chrono.

I would stay away from std::experimental, boost can do that more portable until std:: absorbs those features properly.

**Comment by christ2go** [comment]
Please also note, that boost is required for merging #554. Else I agree with @Grumbel.

**Comment by SuicSoft** [comment]
@Grumbel I just changed the boost::format to std::format and removed the % and other stuff. And can you explain what you mean by "lots of passing std::string into format() and then into printf() which doesn't work either, that only accepts standard C types." since my code does work and acts the same as the normal SuperTux git

**Comment by Grumbel** [comment]
Take this:
```
#include <iostream>
#include <string>
#include "format.hpp"

int main()
{
  std::string str = "Hello World";
  std::cout << format("%s\n", str) << std::endl;
  return 0;
}
```
And run it:
```
$ ./main 
Џ��
```

`format()` is handing the data over to `printf()` and `printf()` is an old C function that doesn't deal with C++ types like std::string and just produces gibberish.

**Comment by maxteufel** [comment]
No. We didn't ask for this, and there does not seem to be any point in removing the boost dependency.

**Pull request closed without merging**
