### PR TITLE
Fix fish dissapear when going to the bottom of the sector in water

### LINKED ISSUE #2800: Chasing fish dissapears after killing Tux
So while editing a new level i found out that when a chassing fish kills Tux it dissapears? Note that this is when Tux is swimming and it does not happen 100% of the time. I dont know what exactly caused this to happen nor was this bug already discovered. Im assuming because i used a slightly older nightly build but i really dont know. I even have a video of it.

https://github.com/SuperTux/supertux/assets/161161755/d84455c1-f362-4f90-b5be-c5463d6ca2b9

### PR DESCRIPTION
**Pull request by MatusGuy**
fixes #2800

### CODE REVIEW

**Comment by rapic45** [comment]
Thanks marty :)

**Comment by Vankata453** [comment]
Perhaps a better way to get around this issue would be to modify `BadGuy`'s out-of-sector check (`badguy/badguy.cpp:190`)?

**Comment by MatusGuy** [comment]
No

**Comment by Vankata453** [comment]
You mean it's not a better solution?

**Comment by MatusGuy** [comment]
It's not a better solution because this behaviour is specific to the fish and we need to check if its on water

**Review by Vankata453 — APPROVED** [review]

**Comment by tobbi** [comment]
You guys both can't spell "disappear".

**Comment by MatusGuy** [comment]
ok bro

**Review by mrkubax10 — APPROVED** [review]

**Pull request merged**
