### PR TITLE
New features (Part 1/3)

### PR DESCRIPTION
**Pull request by DwarflinDeveloping**
Hello SuperTux-Community.
I have a few changes that I would like to introduce here. If you have any concerns, please feel free to ask.

**Changes to the level editor**
New features:
- completely new desert theme
- many signs for the level editor
- added the "data/images/tiles/signs/buttjump.png" file

**Authors mention at music and sound effects (ogg-files)**
I have named the authors of many different musics and sound effects. This should help users to find the original works quickly. (See changes [here](https://github.com/SuperTux/supertux/commit/27a2e89535bc9fe3cfcad1e6f647f650c98c6b13) & [here](https://github.com/SuperTux/supertux/pull/1595/commits/200366d7314f3f0628f2b70d9e703a0e2f6e2879))

Any issues? -> please write a comment!

### CODE REVIEW

**Comment by serano01** [comment]
We came to the conclusion that we will not merge this, since the additional signs are not needed, also your desert tile-set clashes with our graphic style. Therefore I'm closing this.

**Comment by DwarflinDeveloping** [comment]
I was told several times by other developers that the "data/images/tiles/signs/buttjump.png" would be needed.

**Comment by DwarflinDeveloping** [comment]
Why does a desert tile conflict with your graphic style? I know that the focus of the game is on the ice landscape, but then the forest tiles would also conflict with your graphic style.

**Comment by serano01** [comment]
I meant the quality of the graphics and the overall style, not what it represents.

**Pull request closed without merging**
