### PR TITLE
Fix ability to put portable object into other

### PR DESCRIPTION
**Pull request by mrkubax10**

### CODE REVIEW

**Comment by Semphriss** [comment]
What behavior does this change in the game?

**Comment by mrkubax10** [comment]
Fixes this:
https://user-images.githubusercontent.com/63350514/124615349-76c39080-de75-11eb-81b5-a8c250020ed3.mp4

**Comment by Ordoviz** [comment]
I support the change. While I found this way of stacking rocks very convenient, it is not very intuitive and it can lead to weird interactions if you throw a rock from a very small distance into a rock stack. Level designers should stop making levels requiring rock stacks.

**Comment by mrkubax10** [comment]
This change doesn't only apply to rocks.

**Comment by weluvgoatz** [comment]
> Fixes this:
> https://user-images.githubusercontent.com/63350514/124615349-76c39080-de75-11eb-81b5-a8c250020ed3.mp4

Why is this an issue? I thought this way of stacking rocks was nice...

**Comment by Semphriss** [comment]
How is this a bug/broken behavior? This is the default way of handling colliding collideables...

**Pull request closed without merging**
