### PR TITLE
Fix missing music due to path changes

### LINKED ISSUE #1172: The music is missing in many levels
Since the music has been moved into subfolders, SuperTux does not find the music files in the levels which I have downloaded.
For legacy support, the music file could be searched in the subfolders if it isn't found.

### PR DESCRIPTION
**Pull request by HybridDog**
If the music has not been found, a fallback path is searched for.
This should fix #1172; please test it.

### CODE REVIEW

**Comment by tobbi** [comment]
Thank you so much for this! I had the same idea in mind but didn't manage to do it.

**Comment by HybridDog** [comment]
I forgot that the fallback paths all have a slash delimiter, so they probably do not work on Windows.

**Comment by tobbi** [comment]
No problem, can you fix it?

**Comment by HybridDog** [comment]
I've just seen that the paths in the level files are slash-delimited, too, (e.g. `(file "music/antarctic/chipdisko.ogg")`), so it could already work on Windows, but I haven't tested it.

**Comment by tobbi** [comment]
@Rusty-Box You use this thing that they commonly refer to as "WIndows". Can you test it?

**Pull request merged**
