### PR TITLE
Package game zip on Windows as an alternative

### PR DESCRIPTION
**Pull request by MatusGuy**

### CODE REVIEW

**Comment by tobbi** [comment]
Well, it's not a truly portable file since it still saves data outside the respective directory.

**Comment by MatusGuy** [comment]
???

**Comment by MatusGuy** [comment]
Oh. But that's not my goal

**Comment by MatusGuy** [comment]
Attention testers: Please test the msi, the run_supertux.bat script and the run_supertux_portable.bat script.

**Comment by MatusGuy** [comment]
@Frostwithasideofsalt Could you attempt to test this once again? The missing DLL errors you showed me are very bizarre and I can't see them when I try running the program in my machine

**Review by bruhmoent — APPROVED** [review]

**Review by Frostwithasideofsalt — APPROVED** [review]
yup yeah mhm it works yup true there you go yessir

**Review by Rusty-Box — APPROVED** [review]

**Pull request merged**
