### PR TITLE
Snail stomping

### PR DESCRIPTION
**Pull request by Zwatotem**
Snail now hides in the shell if he finds himself in danger of stomping. You can however still stomp him with buttjump action. Please test and review.

### CODE REVIEW

**Comment by busybody42** [comment]
...why does this even exist? It should be smart enough to NOT do that, because it knows it'll probably just kill it's own team mates if it does that... (it acts like a mr ice block, kinda, when jumped on in it's shell)

**Comment by Zwatotem** [comment]
@busybody42 What are you talking about?

**Comment by busybody42** [comment]
... Basically, this would probably trivialize the enemy's koopa shell-like gimmick...
It would go flying the instant it's jumped on the first time...
also, wouldn't this be unfair for smalltux players?

**Comment by tobbi** [comment]
Is this ready to be merged?

**Comment by Zwatotem** [comment]
I'm looking for someone to create graphic for this PR.

**Comment by tobbi** [comment]
@Rusty-Box ^^ So you don't get bored!

**Comment by Alzter** [comment]
Suggestions for snail stomping:
- Normal Snail bounce makes Tux bounce off the Snail's shell, doesn't hurt player
- Buttjump acts like normal stomp
- Make kicking Snail shells not send them flying upwards as it makes has no clear benefit to the player and ends up being frustrating as it can miss enemies and hit you

**Comment by busybody42** [comment]
Altzer, my reply to your suggestion is that kicking it does make it fly upwards, (but we do need to have a thing that explains that mechanic) but jumping on it doesn't make it go upwards, yet it still skids...

**Comment by Zwatotem** [comment]
@Alzter: First two points are just, what's applied. Either third point or @busybody42's suggestion (or some variation of it) is considerable.

**Comment by Zwatotem** [comment]
I'll bring the code to the end and merge with current sprites. They deserve separate PR.

**Pull request merged**
