### PR TITLE
Update worldmap tiles to fit art style + deprecation

### PR DESCRIPTION
**Pull request by Rusty-Box**
This PR aims to updates all worldmap tiles to make sure tha even they now are consitent with all the other assets, along side a couple missing additions, like the Corrupted Underground. **It also deprecates a bunch of old assets!**

TO-DO:

- [x] Snow
- [x] Ice Cave
- [x] Forest + Corrupted Forest
- [x] Underground Forest + Corrupted Underground
- [x] Granito Houses + Ruin Structures
- [x] Corrupted Granito Houses + Corrupted Ruin
- [x] Corrupted Roots
- [x] Paths
- [x] Water

---

- [x] Proper deprication of worldmap tiles and assets
- [x] Autotiling for all compatible worldmap tilesets (big thanks to @tylerandari13)

### CODE REVIEW

**Comment by VincentAraneo** [comment]
What a great art you make Rusty!😁

**Comment by Brockengespenst** [comment]
Looks pretty fine so far. I just saw three small glitches:
iceworld
rooted-forest

**Comment by Rusty-Box** [comment]
That is intended. I removed the paths from the igloo and latter tiles as it is more handy to not have path variants for each. This has been addressed for the new world maps that are currently in the works but I can fix that for the old ones as well for the time being.

**Comment by Rusty-Box** [comment]
Those should be fixed now.

**Comment by Brockengespenst** [comment]
> Those should be fixed now.

Alright, looks good now. :-)

**Comment by Rusty-Box** [comment]
@Vankata453 You know better how this whole depreciation thing works? Can you tell me if I did it right, cuz I personally think I probably have.

**Comment by Vankata453** [comment]
Cannot fully check this now, but one thing you should do is move all the .deprecated tile image files into a deprecated/ sub-directory.

**Comment by Rusty-Box** [comment]
> Cannot fully check this now, but one thing you should do is move all the .deprecated tile image files into a deprecated/ sub-directory, under the original folder of the image.

@Vankata453 Do I still give those files the ".deprecated"-file extension then, when I put them in a deprecated/ sub-directory?

**Comment by Vankata453** [comment]
> @Vankata453 Do I still give those files the ".deprecated"-file extension then, when I put them in a deprecated/ sub-directory?

Yes.

**Comment by Rusty-Box** [comment]
Gonna add corrupted tower, ruin and Granito houses as well cuz I forgot that I also need that for story mode

**Review by Frostwithasideofsalt — APPROVED** [review]

**Review by MatusGuy — APPROVED** [review]

**Pull request merged**
