### PR TITLE
(WIP) Use SDL_ttf for font rendering 

### PR DESCRIPTION
**Pull request by tobbi**
With this PR, our ancient and ugly font rendering code will be replaced with SDL_ttf. 

xref #130 #305 #94 #97

### CODE REVIEW

**Comment by Hume2** [comment]
I don't see any text. At least I remember the order of the buttons. However, the size of the menu seems to be correct.

**Comment by tobbi** [comment]
Please make sure that you have SDL_ttf installed. Also, check both renderers please.

**Comment by Hume2** [comment]
It works now, we just need a font that supports latin-extended.

**Comment by tobbi** [comment]
Note: Misrenderings with Japanese font in info boxes are not font problems but po file problems. Maybe, before merging this PR we should update the po files from transifex.

**Comment by tobbi** [comment]
https://github.com/lxnt/ex-sdl-freetype-harfbuzz

**Comment by tobbi** [comment]
Of interest is also: https://github.com/wutipong/drawtext-sdl2-freetype2-harfbuzz (which might seem to be easier)

**Comment by tobbi** [comment]
Japanese font to use: https://osdn.jp/downloads/users/8/8636/genjyuugothic-20150607.7z (Genjyu Gothic Normal).

**Comment by tobbi** [comment]
Since SDL_ttf is a direct wrapper on top of freetype, I could as well copy the code over from the relevant TTF_* methods.

**Comment by Savsish** [comment]
How about fixing Windows MSVC builds

**Comment by tobbi** [comment]
If you're referring to the MSVC builds with fretype and all that: The dependency package needs to be updated, and we will only do that if the modern fonts branch is saved.

**Comment by maxteufel** [comment]
@Savsish Please build the dependencies for Windows yourself, if you want to test this now. Otherwise, you'll have to wait. However, we won't tell you how to compile the dependencies, you can figure that out using Google. In the future, please open a separate issue for such problems.

**Comment by tobbi** [comment]
Video of the current font: https://www.youtube.com/watch?v=0oyzlA7w2I4&feature=youtu.be

**Pull request closed without merging**
