### PR TITLE
Windowsdylan icecrash patch

### PR DESCRIPTION
**Pull request by windowsdylan**
Shortened the icecrash sound so when the stalactite falls, the sound plays at the exact time it hits the ground.

### CODE REVIEW

**Comment by tobbi** [comment]
`[ci skip]` ? 😛

**Comment by windowsdylan** [comment]
> `[ci skip]` ? 😛

Huh?

**Comment by Semphriss** [comment]
@windowsdylan Add "ci skip" to your commit messages so that the build system won't waste time rebuilding the entire game only for an asset change

**Comment by Ordoviz** [comment]
It’s also a good idea to squash the commits together under a meaningful description like: “[ci skip] Shorten icecrash sound”. However, as @windowsdylan is clearly new to Git, the maintainers should do this.

**Pull request merged**
