### PR TITLE
Replace RelWithDebInfo builds with Release builds

### PR DESCRIPTION
**Pull request by Semphriss**
RelWithDebInfo include debug data separately from the executable code, which needs a debugger to be interpreted properly.

The debug data does not affect stack traces generated by the program itself, but increases the executable by more than 100Mb, which is wasted if the user does not intent to run the exectuable inside a debugger.

### CODE REVIEW

**Comment by tobbi** [comment]
Okay, I admit I had no idea what I'm doing. Any idea how to get proper symbol names on stack unwinding when Tux has swallowed a bad fish can?

Or is that a no-*can*-do?

**Comment by MatusGuy** [comment]
On windows I just needed to add a few things and package the pdb file for supertux2.exe

**Comment by tobbi** [comment]
> On windows I just needed to add a few things and package the pdb file for supertux2.exe

So for Windows this is already done? How about MacOS or Linux?

**Comment by MatusGuy** [comment]
SuperTuxKart has an implementation for what you are talking about at https://github.com/supertuxkart/stk-code/blob/master/src/utils/crash_reporting.cpp

**Comment by Semphriss** [comment]
On Linux at least, it looks like a copy-paste of `addr2line`, which is already available on most developer systems that use GCC.

I don't think there is any need to ship debug data, since everything can be obtained locally from the mangled data using local tools like `addr2line` or, preferably, GDB. (You can grab a mangled crash report from a user's Release build and use a local RelWithDebInfo build in GDB to get the file and line info.)

**Review by MatusGuy — APPROVED** [review]

**Pull request merged**
