### PR TITLE
Update Penny's Look

### PR DESCRIPTION
**Pull request by serano01**
- this will change Penny's Look from purple to black with a small scarf
- added a small idle animation similar to Tux' winking as well

### CODE REVIEW

**Comment by qwertychouskie** [comment]
Penny still looks quite pixelated.  I wonder if it would be easier to take Tux as a base and add/tweak things to turn it into Penny.  This would hopefully avoid the pixelation issue.

**Comment by Alzter** [comment]
> Penny still looks quite pixelated. I wonder if it would be easier to take Tux as a base and add/tweak things to turn it into Penny. This would hopefully avoid the pixelation issue.

I feel like it'd be more optimal to just draw her a new design. This concept art by grumbel shows what she could potentially look like, a bit slimmer than Tux with more angular features.

image

**Comment by Zwatotem** [comment]
For me this graphic looks okay. Pixelated look should be easily repairable with some form of anti-aliasing effect applied.

**Comment by Alzter** [comment]
> For me this graphic looks okay. Pixelated look should be easily repairable with some form of anti-aliasing effect applied.

Even then that doesn't cover the fact that both Penny and Nolok are nearly inanimate

**Comment by serano01** [comment]
I'm closing this, since it needs more work.

**Pull request closed without merging**
