### PR TITLE
Solve issue #1523

### PR DESCRIPTION
**Pull request by omeritzics**
Hello, this is a pull request to solve the build error on Travis CI and to solve issue #1523.
----------
There was a bug of the Hebrew translation of supertux2.desktop, there is a fix in this pull request.

There is an issue with the font choosing for Hebrew in resources.cpp, so this tries to solve this are in this pull request too.

### CODE REVIEW

**Comment by omeritzics** [comment]
Hello, this is a pull request to solve the build error and to solve issue #1523.

**Comment by weluvgoatz** [comment]
Hello, I don't know if all these PRs are exactly the same but they all seem very very similar, so I would like to ask that you stop creating and closing and opening more and more PRs for the same if not similar things.  Just make 1 PR!!!!  And work from there.  Of course we encourage lots of community contribution but making a mountain of PRs like this is just annoying.

**Comment by omeritzics** [comment]
Hello, I am sorry for this, didn't plan to open sevral pull requests for the same thing. I opened this because something went wrong in the other pull request.

**Comment by Semphriss** [comment]
@omeritzics Please do extensive testing on your branch before submitting a PR. It feels quite spammy to see all those pull requests being opened and closed, especially since we don't always know what's going on.

If you want, join us on social media so we can give you feedback on your submissions. That could help reduce the need to open many pull requests as the discussions would occur before opening the PRs.

**Comment by omeritzics** [comment]
Hello, I won't submit a lot of pull requests like the pull requests to replace the Hebrew font (I tested it on my computer).
I closed the other pull request to solve the Hebrew international support issue because something went wrong there (An important file was accidentally deleted in the branch I submitted the pull request from).

**Comment by tobbi** [comment]
@omeritzics Please do us a favour and test your changes locally before submitting them here.

**Comment by omeritzics** [comment]
OK, I'll test it.

**Comment by tobbi** [comment]
If you need help: There's a discord link on supertux.org

**Comment by tobbi** [comment]
Please stop editing your PR in-place and test them locally before pushing. We can help you set things up.

Please go here: https://matrix.to/#/!BfYVBjzEVacHrvDBYw:matrix.org?via=matrix.org&via=t2bot.io&via=synapse.vpzom.click and we can talk you through.

**Comment by omeritzics** [comment]
> Please stop editing your PR in-place and test them locally before pushing.

Hello, the last commits are tested commits. They was to revert the test passing files.

**Pull request closed without merging**
