### PR TITLE
Remake VOC OST music

### PR DESCRIPTION
**Pull request by mansiw21**
Making new versions of the VOC themes:

- [ ] voc-boss.ogg
- [ ] voc-dark.ogg
- [ ] voc-daytime.ogg
- [ ] voc-daytime2.ogg
- [x] voc-night.ogg

### CODE REVIEW

**Comment by Asemif** [comment]
No! Please don't remake this.

**Comment by mansiw21** [comment]
> No! Please don't remake this.

Nuh uh!

**Comment by Asemif** [comment]
Sorry, I listened to your version of this masterpiece and changed my mind

**Comment by mansiw21** [comment]
> Sorry, I listened to your version of this masterpiece and changed my mind

Oh, thank.s 💪🗿

**Comment by Rusty-Box** [comment]
This seems to have been discontinued. Closing this unless creator wishes to continue and re-open.

**Comment by VincentAraneo** [comment]
I could continue with the progress of the remasters of VOC music, I have a bit of experience in making songs, and I think about doing the remasters of Voc Daytime 1 and 2, Voc Dark and Voc Boss. It could help to remaster the other voc songs, well if you guys want

**Comment by tulpenkiste** [comment]
@VincentAraneo Need I remind you of our previous interaction where I explicitly stated that you were actively in violation of the GitHub Terms of Service (due to not being old enough to use the service)?

Please avoid utilising GitHub at all until you turn 13 years old (at the minimum).

**Pull request closed without merging**
