### PR TITLE
Another level for the forest world

### PR DESCRIPTION
**Pull request by StephenPs**
well, this is my first time contrubiting, but this is the forest's castle.

May need to work on the boss though

### CODE REVIEW

**Comment by weluvgoatz** [comment]
Maybe try posting to the forum first. I have tried your level, the design could be better. But @Rusty-Box is already working on the castle. You also need to use the new castle tiles, and background. This could be in an addon, but I doubt the team is going to use this for the official forest, especially when someone's already working on it. Sorry.

**Comment by 165your4** [comment]
What's wrong with the existing castle levels?

**Comment by StephenPs** [comment]
Is he finshed yet

**Comment by StephenPs** [comment]
I think that we should just reuse The Silent Walls

**Comment by weluvgoatz** [comment]
The existing castle is outdated and unusable. And why would some use an old bad tileset when there is a newer one? The Silent Walls is not long enough to be the standalone castle level and the ghost tree section is awful-looking...

**Comment by 165your4** [comment]
If the new castle levels are anything like the new forest levels they will be well-designed but charmless, boring, and devoid of any challenge. The Silent Walls introduces a new game mechanic in a difficult and interesting way - can any of the new levels say the same? FWIW The Ghost Tree section was added to The Silent Walls fairly recently and it shows. It's really rather tacked on. In my opinion it would be better for the boss to be in it's own level, like the Yeti in Icy Island.

**Comment by weluvgoatz** [comment]
Yes, that is true, the newer levels are very easy, and the ghost tree
should be it's own level.  But I am not a SuperTux dev. As far as I know,
this is @Rusty-Box's choice and not mine.  If you think you can make better
levels, please show me.

**Comment by busybody42** [comment]
Umm... What about the unused level "a room of stars" in the editor?

**Comment by weluvgoatz** [comment]
I am working on a ghost forest level which introduces the Ispy (eye thing from Silent Walls). The Silent Walls imo is an easy level. Room of Stars is outdated but is a good level.

**Comment by StephenPs** [comment]
I did this on Supertux 0.5.1, not the SVN verson. Give me credit, i didn't have  the new tilesets

**Comment by busybody42** [comment]
Rooms of stars could be a midway castle level, like in the new super Mario bros games! (Every world except world 9 had a fortress level in the middle of each world!)

**Comment by weluvgoatz** [comment]
Why do you use snow enemies and snow background?? It's the forest world. I still think its a nice level tho.

**Comment by StephenPs** [comment]
Well, here we go again....

**Comment by weluvgoatz** [comment]
Again with what? Your level was pretty good, probably better than my
levels...

**Comment by weluvgoatz** [comment]
There are other plans for the forest world, perhaps close this @tobbi or @Rusty-Box or @serano01

**Comment by Rusty-Box** [comment]
Closing this. The forest world already has enough levels which are set to be.

**Pull request closed without merging**
