### PR TITLE
New coin sprites

### PR DESCRIPTION
**Pull request by Alzter**
Updated coin sprites with 16 frames of animation

### CODE REVIEW

**Comment by tobbi** [comment]
What directory are those in?

**Comment by Alzter** [comment]
> What directory are those in?

They should be in sprites/objects/coin and sprites/engine/hud.

**Comment by qwertychouskie** [comment]
It looks like you accidentally put these in `coin` (new top-level folder) rather than `sprites/objects/coin`.

**Comment by serano01** [comment]
I've added the sprites to the game, thanks Altzer for the contribution.

**Pull request closed without merging**
