### PR TITLE
Add music "Calm Ocean" by Chitan

### PR DESCRIPTION
**Pull request by Chitan96**
This is my contribution for a water level theme for the Tropical Paradise level set. Good amount of inspiration with this came from "Aquatic Ambience" from Donkey Kong Country's OST. This also happens to be my first ever pull request so let me know if I made any mistakes or if I need to change anything. Thanks.

### CODE REVIEW

**Review by Frostwithasideofsalt — APPROVED** [review]

**Review by bruhmoent — APPROVED** [review]
I recommend changing the filename to `calm_ocean`

**Review by bruhmoent — APPROVED** [review]

**Review by Frostwithasideofsalt — APPROVED** [review]

**Comment by serano01** [comment]
Shouldn't this be placed in the "Tropical"-Folder instead of "Misc"?

**Comment by MatusGuy** [comment]
Not really. I believe we discussed it wasn't gonna be in tropical island because of the general vibe of the track

**Comment by Vankata453** [comment]
@Chitan96 What is the license of this song?

**Pull request merged**
