### PR TITLE
Option to enter ghost mode from cheat menu

### PR DESCRIPTION
**Pull request by Karkus476**
Made a pull request, as I'm not sure if this is wanted or not.

### CODE REVIEW

**Comment by brmbrmcar** [comment]
It should be called edit mode. Otherwise people might think its the ghost forest transition.

**Comment by maxteufel** [comment]
@brmbrmcar edit mode is already something different. And people that don't know what it does probably shouldn't have this enabled anyway.

**Comment by Hume2** [comment]
:+1: This could be useful.

**Comment by brmbrmcar** [comment]
What is the difference between ghost and edit mode?

**Comment by maxteufel** [comment]
Ghost mode is one-time, edit mode is valid during the full time you play the level and will automatically put you in ghost mode when you'd die.

**Comment by brmbrmcar** [comment]
Is that preferred over edit mode?

**Comment by Karkus476** [comment]
@maxteufel So, 0.5.0?

**Comment by maxteufel** [comment]
@Karkus476 I think we can actually put this in 0.4.1.

@SuperTux/core, @SuperTux/developers: objections?

**Comment by LMH0013** [comment]
Seems like a logical change, I doubt you'll find any objections.

**Comment by MiroslavR** [comment]
This could be useful for translators who want to test their translations without having to go through the level by normal means.

**Comment by Grumbel** [comment]
Merged.

**Pull request closed without merging**
