### PR TITLE
Fix ambient sound (Issue #806)

### PR DESCRIPTION
**Pull request by mrkubax10**
This pull request adds features from maxteufel's comment: [comment](https://github.com/SuperTux/supertux/issues/806#issuecomment-394170973) to AmbientSound

### CODE REVIEW

**Comment by Rusty-Box** [comment]
I like this change to the ambient sound. However, there then should also be a way to play an ambient sound such as rain for an entire sector without its volume changing. I personally think this should be a sector option, like how we handle editing the music.

**Comment by mrkubax10** [comment]
Idea with ambient sound for sector is nice, I will try to add this

**Comment by tobbi** [comment]
Can this be merged?

**Comment by mrkubax10** [comment]
Problem is that it will make existing ambient sounds not working.

**Comment by tobbi** [comment]
What needs to be done in order to fix them?

**Comment by mrkubax10** [comment]
Ambient sound now uses property effect-distance instead of multiple properties to determine volume at certain distance, so every ambient sound needs to have this property set.

**Comment by tobbi** [comment]
There's actually not that many levels that use ambient-sound. Not in the data directory of the main game anyway. Not sure about add-ons.

**Comment by Semphriss** [comment]
Will this be overridden by #2172 ?

**Comment by Vankata453** [comment]
We should probably revive this PR, ambient sound does seem to need fixing.

**Comment by mrkubax10** [comment]
> We should probably revive this PR, ambient sound does seem to need fixing.

Yes but probably as a different PR

**Pull request closed without merging**
