### PR TITLE
Add Afrikaans translation

### PR DESCRIPTION
**Pull request by martinvanzijl**
My Afrikaans is a little rusty, so this should be reviewed.

### CODE REVIEW

**Comment by martinvanzijl** [comment]
@tobbi Thanks for the correction. I've made the language request on transifex now.

**Comment by tobbi** [comment]
I would like to add you but for some reason can't. Did you set your profile to private?

**Comment by martinvanzijl** [comment]
I've just made it public. Can you please try again?

Op So. 1 Sep. 2019 om 20:37 het Tobias Markus <notifications@github.com>
geskryf:

**Comment by tobbi** [comment]
There we go! :)

**Comment by tobbi** [comment]
Now that translation is possible on Transifex, I'm closing this.

**Pull request closed without merging**
