### PR TITLE
Use SDL_OpenURL() to open URL cross-platformingly

### PR DESCRIPTION
**Pull request by pelya**
Including Android support

### CODE REVIEW

**Comment by Semphriss** [comment]
Can `SDL_OpenURL()` also open local files? (`open_path` is also used to show up the system file manager, or certain files with their default app)

**Comment by pelya** [comment]
It should be able to open local files

https://wiki.libsdl.org/SDL_OpenURL

**Comment by Semphriss** [comment]
Reading the documentation, `SDL_OpenURL()` could open files only if they are prefixed with `file:///`; I'll conduct tests and research to see what's best to handle this.

Also, I believe the team decided to split the code that opens files from the code that opens URLs, given problems with WASM; it might be a good opportunity to increase the quality of the code.

Is it fine if I push changes to your branch directly, or would you prefer that I create a different branch?

**Comment by pelya** [comment]
It's fine, I only care that the opening URLs works on Android.

**Comment by Zwatotem** [comment]
Looks okay

**Pull request merged**
