### PR TITLE
Player: ungrab grabbed_object when entering ghost mode

### LINKED ISSUE #307: Crash while holding Mr. IceBlock in edit mode
I am using supertux2 0.3.5a, version packaged in Fedora 23, Linux 4.2.8-300.fc23.x86_64, no core dump generated. SuperTux crashed while I was in the level “On The Road Again” in Bonus Island II.

Steps to reproduce (seems to work in any level):

1. Open the console and enable edit mode with `edit()`.
2. Squish one of the Mr. IceBlock badguys in the level.
3. Carry it by running into it while pressing the action button.
4. Jump into one of the holes and fall to the bottom of the screen.

At this point, the game should crash. This does not seem to be due to switching to ghost mode while carrying Mr. IceBlock, since opening the console and executing `ghost()` while carrying Mr. IceBlock does not make the game crash. Furthermore, dying in another way than by falling to the bottom of the screen while in edit mode and carrying Mr. IceBlock does not make the game crash.

### PR DESCRIPTION
**Pull request by maxteufel**
Fixes #307

### CODE REVIEW

**Comment by Hume2** [comment]
Seems OK to merge.

**Comment by tobbi** [comment]
This works when you use the cheat menu, however, it doesn't work when you set ghost() from the in-game console. Tux appears to get hurt and immediately goes mortal again. All is fine when you don't grab an object.

So: r-

**Comment by maxteufel** [comment]
If you press the release key it's intended to go mortal immediately.

**Comment by tobbi** [comment]
Screencast: http://screencast.com/t/ZlQKwQ1Lro

**Comment by maxteufel** [comment]
> Viewing this content requires Adobe Flash Player. You can download Adobe Flash Player from http://get.adobe.com/flashplayer/.

No thank you.

**Pull request merged**
