### PR TITLE
Create storm-cloud.png

### PR DESCRIPTION
**Pull request by DevynCJohnson**
[ci skip]
Added a storm cloud

Please feel free to give me feedback so that I can contribute images that match your standards.

storm-cloud

### CODE REVIEW

**Comment by DevynCJohnson** [comment]
If this is not the proper method for contributing/uploading images, please let me know how you would like it done.

**Comment by maxteufel** [comment]
Generally, in changes that don't affect the build process add a `[ci skip]` line to the commit message.

Secondly, I think the actual better way is to join IRC (chat.freenode.net, channel: #supertux), discuss with us what art we need, share drafts as a link in IRC and when everyone's OK submit a pull request.

**Comment by tobbi** [comment]
I think it's great and adds some diversity to the game :-)

**Comment by sydneyjd** [comment]
Looks good to me! 
You are doing it properly, but we need to add the image to ~/supertux/data/images/tiles.strf before the editor/game will recognize it. We can do it, its just something for you to know.
 
Keep up the good work!

**Comment by DevynCJohnson** [comment]
Thanks for the info @sydneyjd !

@maxteufel , I do not intend on being a permanent or long-term developer for SuperTux. I just like to help various open-source projects. However, I will look-into temporarily joining the IRC chat-room

**Comment by DevynCJohnson** [comment]
Whoops, I did not intend on closing the pull-request. I will reopen it.

**Comment by Hume2** [comment]
Further use "git commit amend" and "git push -f".
You have already created another pull request about the same, but with update info. So I'll close this and continue in #203 .
Please don't flood the repository by the variations of a single pull request.

**Pull request closed without merging**
