### PR TITLE
ST OST - Some songs i made for the music overhaul

### PR DESCRIPTION
**Pull request by Curly68**
They aren't many of them at the moment, but i think what i made so far can really help a lot when it comes to the music overhaul of this game for 0.7. I will eventually come with more songs
For now the songs that are here and their purpose are as follows:

- skylevel.ogg: Meant for the sky levels in the game
- sunset.ogg: Meant for the sunset levels in the game, also a replacement for voc-daytime2.ogg in the main story (third party worlds would probably still have the original voc-daytime2.ogg as a fallback)
- night.ogg: Meant for the night levels in the game, replacement of voc-night. Ditto as above
- worldmap_ice.ogg: Meant as a proper world map theme for World 1, as a replacement for the Salcon theme

License is CC-BY-SA 4.0

### CODE REVIEW

**Comment by tobbi** [comment]
Can you maybe specify the licenses in the data/AUTHORS.txt ?

**Comment by Vankata453** [comment]
Perhaps `world-1-worldmap.ogg` should be renamed - music isn't specific to worlds. Maybe `worldmap-ice.ogg`?

**Comment by Vankata453** [comment]
Also recommend adding newlines at the end of the `.music` files, so Git doesn't complain.

**Comment by Vankata453** [comment]
> About the newlines, i checked the .music files and they appear to be there.

Going to "Files Changes", it shows a newline is missing at the end for all, except `worldmap_ice.music`.

----

By the way, do we still want to go by the VOC naming and keep it `voc-night-revamp.ogg`? Maybe something to be discussed.

**Comment by Curly68** [comment]
Oh i see.

And about the naming, maybe yeah i could rename my revamp song to `night.ogg`

**Comment by Curly68** [comment]
Renamed `voc-night-revamp.ogg` to `night.ogg` and added missing newlines to the .music files

**Comment by Rusty-Box** [comment]
For filename consistency, my only request is to replace the "-" with "_". Otherwise I approve!

**Comment by Curly68** [comment]
Okay just did that

**Review by Rusty-Box — APPROVED** [review]

**Review by Frostwithasideofsalt — APPROVED** [review]
peak

**Pull request merged**
