### PR TITLE
New Levels for Forest World

### PR DESCRIPTION
**Pull request by weluvgoatz**
Since @Rusty-Box and @serano01 are reworking the levels and story on Forest World, I would like to help them. Here are some levels and cutscenes I have designed for the Forest World. Please check out these commits and I hope you will add them!

### CODE REVIEW

**Comment by rustybox** [comment]
I think you have tagged the wrong person here :)

**Comment by Rusty-Box** [comment]
This is me :)

**Comment by weluvgoatz** [comment]
oops. fixed that. sorry...

**Comment by serano01** [comment]
Can you send me your levels? I will check them then.

**Comment by weluvgoatz** [comment]
here.

**Comment by tobbi** [comment]
@weluvgoatz This didn't work. Can you try putting them in a zip file and attach (drag'n'drop) that file here?

**Comment by weluvgoatz** [comment]
i completely lost them. i sent them to @serano01 via gmail, hopefully he has them. if not, im screwed. i lost them when i got a new update.

**Comment by Rusty-Box** [comment]
I have them.

**Comment by weluvgoatz** [comment]
thank goodness, can you put them here?

**Comment by weluvgoatz** [comment]
wait, when you view a file press raw and then download it. It worked for me and I got my levs back. go to files changed and do it one by one.

**Comment by serano01** [comment]
Very cool levels, but "A Ghosty World" and the "Corrupted Forest" seems to be the same level, apart from a few changes. I really likde "The Secluded Garden" and "Fresh Spring Air".

**Comment by weluvgoatz** [comment]
@Serano01: About "Corruption of the Forest", that's the point. it's an
IMPROVED version. And btw, It has lots of changes. Terrain is the only
thing not changed.

**Comment by weluvgoatz** [comment]
i made another pr on this. check that out.

**Pull request closed without merging**
