### PR TITLE
Rock tiles are no longer solid. FINALLY!

### PR DESCRIPTION
**Pull request by Semphriss**
NOTE: No level has been edited in this commit. Some levels (such as the first level of the forest world) might have buggy graphics or even might be rendered impossible at all due to this.

### CODE REVIEW

**Comment by Ordoviz** [comment]
[The people have spoken](https://forum.freegamedev.net/viewtopic.php?f=67&t=13262).

**Comment by tobbi** [comment]
Since making stones non-solid will impact existing levels to quite an extent, I will not merge this. Sorry 'bout that.

**Comment by Semphriss** [comment]
Reopened after internal discussion

And this time, **marked as WIP** to make it clear I intend to make sure no level relied on rocks being solid, and to fix those that did.

**Comment by Semphriss** [comment]
Ready for review; all forest levels have been adapted. Let me know if something else needs attention.

**Pull request merged**
