### PR TITLE
Fix music not playing

### PR DESCRIPTION
**Pull request by mrkubax10**
Fixes issue when some music doesn't want to play

### CODE REVIEW

**Comment by serano01** [comment]
I think the "tropical" music is affected as well. It isn't just as obvious since no one uses it.

**Comment by mrkubax10** [comment]
Yeah, it is known. This pull requests fixes the issue for every music

**Review by Semphriss — APPROVED** [review]
I didn't check for possible quality optimisations, but the whole thing lookd good.

**Comment by Semphriss** [comment]
Does this conflict with #2146?

**Comment by Zwatotem** [comment]
> Does this conflict with #2146?

No, it shouldn't.

**Pull request merged**
