### PR TITLE
Stop player movement and hide player when door opened

### LINKED ISSUE #229: Stop doors fom blacking out the screen when they aren't being used
It is extremely annoying in some levels where there is a door near a jump, and you cannot see what you are doing, making the jump very difficult.

### PR DESCRIPTION
**Pull request by Karkus476**
We need a door animation with tux walking through the door
fixes #229

### CODE REVIEW

**Comment by brmbrmcar** [comment]
This is a terrible idea and DOES NOT fix my issue. It would make it worse, by forcing the player to go through, when it is only actually a problem if the player doesn't want to use the door.

**Comment by Karkus476** [comment]
@brmbrmcar Surely if you don't want to go through the door, you don't press up?

**Comment by brmbrmcar** [comment]
No, because you have jump with up!

**Comment by Karkus476** [comment]
@brmbrmcar Why would you want jump with up? You should set the Up key to another key.

**Comment by brmbrmcar** [comment]
Because it becomes a pain then, as you need to use a different key to navigate the worldmap.

**Comment by Hume2** [comment]
Exactly, since we have this "jump with up" option, we should expect that the people may use it.

**Comment by Karkus476** [comment]
@brmbrmcar. That is most certainly a good point.

**Comment by Karkus476** [comment]
I'm going to close this, because this is obviously not a solution

**Pull request closed without merging**
