### PR TITLE
Fix camera jittering

### PR DESCRIPTION
**Pull request by HybridDog**
This is the PR for #910 and #909.

### CODE REVIEW

**Comment by HybridDog** [comment]
> Can you please try to undo the first commit? Just interactive-rebase it and delete it.

Done.

**Comment by HybridDog** [comment]
Why did AppVeyor build fail?

**Comment by tobbi** [comment]
Unrelated reasons. I am rescheduling an AppVeyor build.

**Comment by tobbi** [comment]
AppVeyor should be fixed now, so I've merged this.

**Comment by Alzter** [comment]
My camera's still jittering

**Pull request merged**
