### PR TITLE
Add swimming sprites, enhance swimming behaviour, include swimming by default.

### PR DESCRIPTION
**Pull request by Narre**
Add swimming sprites, enhance swimming behaviour (no more 'walking' on water), include swimming by default.

### CODE REVIEW

**Comment by tobbi** [comment]
I think the swimming should look more penguin-like (less human-like) but that might only be me.

What does everyone else think?

**Comment by Rusty-Box** [comment]
@tobbi I agree with you, since it would make the swimming ability more "unique" than (for example) from mario.

**Comment by Narre** [comment]
I agree too, but it wouldn't fit the swimming currently in SuperTux, so I tried to make the images fit the moves.

**Comment by tobbi** [comment]
There is no swimming currently in SuperTux, so you're free to exert your creativity as long as it's in line with our narrow understanding of how we want it ;)

**Comment by Narre** [comment]
I mean the swimming that is coded in the game but not included by default. And I don't know how much I would be able to code, because I don't know much C++. The coding part of this PR was mostly done by Hume2, but we will do some C in school this year, so I should hopefully get better at it. So far, I have only done one bigger project in JavaScript, which I wouldn't call 'programming'. :)

**Comment by weluvgoatz** [comment]
There is already a new (and better) swimming PR, so might this one become closed?

**Comment by Rusty-Box** [comment]
Closing this due to lack of activity and not fitting the attend for how swimming in game should work.

**Pull request closed without merging**
