### PR TITLE
Fix input in editor when dialog is opened

### PR DESCRIPTION
**Pull request by mrkubax10**
Fixes ability to scroll level and werid animation error when escape is pressed when dialog is opened

### CODE REVIEW

**Comment by Semphriss** [comment]
I struggle to reproduce the issue; do you have steps?

I agree the way of doing it that you propose should be favored instead of using `m_enabled`, but I can't find where it fails.

**Comment by mrkubax10** [comment]
https://user-images.githubusercontent.com/63350514/146728283-b8968843-4e06-418e-a888-5271bcaabedf.mp4

**Comment by Semphriss** [comment]
Self-requesting a review because I believe there could be a better way to handle this code-wise, I'll investigate and come back with a solution if I find one.

**Comment by Semphriss** [comment]
Couldn't think of one. I'll come back later if I find one.

**Review by Semphriss — APPROVED** [review]

**Pull request merged**
