### PR TITLE
Use higher quality Retro-Brick

### PR DESCRIPTION
**Pull request by serano01**
Made pieces for it, too.

### CODE REVIEW

**Comment by serano01** [comment]
Based upon RustyBox' work, but since he also made other new blocks, I thought this change would be appropriate, as well.

**Comment by Rusty-Box** [comment]
I don't know about this. As these are meant for providing a more retro look to the RiR add-on an updated sprite should reflect more closely the old brick rather than the new brick design.

**Comment by serano01** [comment]
Yeah, but the whole retro-tileset is brand new, so the old 0.0.4-graphics look odd. And for me, the old brick was, apart from the lower quality, just greener.

**Comment by Rusty-Box** [comment]
I would to play around with it myself to better explain it. It is much brighter and and less detail which I think makes it suit the retro aspect much more

**Comment by serano01** [comment]
retro_brick

Maybe more along the lines of this?

**Comment by Rusty-Box** [comment]
Kinda, but more shiny as the orginal.

**Comment by serano01** [comment]
I'm closing this, since RustyBox has an other solution in mind.

**Pull request closed without merging**
