### PR TITLE
Update pl.po in one level

### PR DESCRIPTION
**Pull request by workonfire**
Minor fixes

### CODE REVIEW

**Comment by Zwatotem** [comment]
Thanks for these translation improvements. If you want to change to help translating we recommend using Transifex (https://www.transifex.com/arctic-games/supertux/). I'm not even sure, if changing `.po` files directly through commits is okay @tobbi?

**Comment by tobbi** [comment]
Supporting .po updates through Github would introduce some inconsistency into the workflow that I'm not willing to tolerate. Therefore, only updates through Transifex are supported.

**Comment by workonfire** [comment]
Oh. Sorry, I didn't know!

**Comment by tobbi** [comment]
Let me know if you'd like to be added on transifex, go to http://transifex.com and create an account.

**Pull request closed without merging**
