### PR TITLE
Tweaked level Miyamoto Monument

### PR DESCRIPTION
**Pull request by brmbrmcar**
A few fixes.

### CODE REVIEW

**Comment by brmbrmcar** [comment]
Problem with the commits...

**Comment by Hume2** [comment]
Why does it contain my commit?

**Comment by brmbrmcar** [comment]
It does. Not sure why. One of the pull requests was a little unusual.

**Comment by Hume2** [comment]
This mistake could have never happened if you was on IRC. Join IRC and we can guide you with the git.

**Comment by brmbrmcar** [comment]
OK, will do.

**Comment by tobbi** [comment]
@brmbrmcar: Please don't use pull requests to your own repository to keep the content up-to-date. We can help you get ready using git, just join us here http://supertux.github.io/contact.html

**Comment by maxteufel** [comment]
Can you **please** remove those merge commits (instead rebase on origin/master if you need to update your PR branch, and **don't** actually update if you don't need to), and squash the commits you actually made to change the level into **one** commit with an appropriate message.

**Comment by maxteufel** [comment]
Furthermore, as this doesn't change anything to the code or the build process, please use `[ci skip]` at the end of your commit message body.

**Comment by brmbrmcar** [comment]
I have no idea what any of that means...

**Comment by maxteufel** [comment]
Then you should rethink submitting a PR, or at least be reading more about git.

**Comment by tobbi** [comment]
Can you please describe what you changed and give screenshots of the changed level? 

If they're good, I can apply the change on my own.

**Comment by brmbrmcar** [comment]
Changed powerup box sprite of coinbox to coinbox.
Put invisible platform beneath star powerup box - Getting it was impossible before.

**Comment by Hume2** [comment]
And you merged again.

**Comment by tobbi** [comment]
I have to disagree with the "invisible wall" change (the other one I couldn't make out). I know that jump is tricky, but it's hardly impossible. And since we're in the cave levels, we can at least add *some* difficulty to the levels.

**Comment by brmbrmcar** [comment]
Are you thinking of the right area?

**Comment by brmbrmcar** [comment]
screenshot from 2015-10-18 20 39 23

**Comment by tobbi** [comment]
Yes. That one. It's perfectly possible to get back on top of the bonus block again and continue.

**Comment by Karkus476** [comment]
Are you using the GitHub desktop app @brmbrmcar ?

**Comment by brmbrmcar** [comment]
Yes.

**Comment by Karkus476** [comment]
@tobbi do you know anything about the GitHub desktop app? @brmbrmcar we want you to find a way to rebate rather than merge as rebasing doesn't change the commit history.

**Comment by brmbrmcar** [comment]
Wait, I am using Github.com.

**Comment by Karkus476** [comment]
Are you using the command line? Use git pull --rebase instead of git pull.

**Comment by brmbrmcar** [comment]
No.

**Comment by tobbi** [comment]
What operating system are you using?

**Comment by brmbrmcar** [comment]
Ubuntu.

**Comment by tobbi** [comment]
Okay, open up a Terminal in Ubuntu, then type git clone https://github.com/SuperTux/supertux/. Wait for it to complete.

**Comment by Karkus476** [comment]
http://supertux.github.io/contact.html scroll to the bottom

**Pull request closed without merging**
