### PR TITLE
WIP Level Editor

### PR DESCRIPTION
**Pull request by Hume2**
All objects are saved as generic game-objects and the reset button temporary saves the current level to test.stl in the .supertux2 directory.

### CODE REVIEW

**Comment by tobbi** [comment]
Regardless of whether we'll merge that in its current state: Please put a space before the opening braces.

**Comment by Flakebi** [comment]
I only want to add that, normally, there are spaces after commas too.

**Comment by Hume2** [comment]
Formating fixed.

**Comment by Hume2** [comment]
Press Esc to exit the editor. Arrow keys to navigate. Many features are still upcomming.

**Comment by Hume2** [comment]
I haven't tested, if the save level really works...

**Comment by Hume2** [comment]
The editor-branch's parent is still not on the tip of master, so if anyone wants to test it, then:
1) git reset --hard 733729d
2) git pull Hume2 editor
3) Build SuperTux, run SuperTux!
To revert it back, type:
1) git reset --hard 733729d
2) git pull supertux master

**Comment by Hume2** [comment]
The next commit will have minimal visual effect, but will be very useful.  I'll start working on tilemap editing after this commit.

**Comment by tobbi** [comment]
Team: Should we defer inclusion of this feature until after 0.4.0 ? There's a lot of code added here with the potential to contain bugs (no offense, Hume). I was hoping that we'd mostly do bug fixing without adding new big features (like this one) until December. What does everyone think?

**Comment by Savsish** [comment]
This feature will be probably included in 0.3.6 release of supertux i think.

**Comment by tobbi** [comment]
There will be no 0.3.6. We'll jump straight to 0.4.0 in December.

**Comment by sydneyjd** [comment]
I hate to admit it, but @tobbi is right
. The level editor would be a *huge* addition to 4.0 though if it could be done. Supertux 2 would not seem complete without a decent level editor. ;)
Im willing to try to "beat the tar" out of the level editor if we get it finished, just so we can try to get it in this release.

**Comment by Savsish** [comment]
If there was supertux 0.0.6 then why there will be no supertux 0.3.6!? >:( There are a lot of bugs and important features that are not yet implented. Anyway i don't to see supertux 0.4.0 as being a crappy obivous beta version that's not so different from current beta 0.3.5 version, so i want that they should release supertux 0.3.6 before Milestone 2, so we would have more time to implement new features, add new badguys etc.

**Comment by Hume2** [comment]
The version is not decimal. It could be 0.3.bananna too.
In fact, there was no big feature since 0.3.0, so this feature would be fine for something like 0.4.0. If it won't be ready since then, it could be still postponed to 0.4.1.

**Comment by tobbi** [comment]
Actually, we are calculating the difference between the last stable release (0.1.3) and this one. There have been a lot of contributions to the code base since then, so we could postpone this feature until the next stable release?

**Comment by Hume2** [comment]
Doeas that mean 0.4.1 or 0.5.0?

**Comment by tobbi** [comment]
Hmm, I'll ponder about that. I'd say since 0.4.1 will include beta features, we can include it there...and when it's ready, release it together with 0.5.0.

**Comment by Hume2** [comment]
OK, it will be officially in the 0.4.1 unsatble snapshot and in 0.5.0 stable.

**Comment by Hume2** [comment]
It got messed up a bit, but it's up-to-date with the supertux/master branch at least.

**Comment by Hume2** [comment]
Feel free to test it.

**Comment by Karkus476** [comment]
@Hume2 Any ideas why the travis build is failing?

**Comment by brmbrmcar** [comment]
0.4.1 unstable? No!

**Comment by Hume2** [comment]
Just wait. I managed to push here some wrong files.

**Comment by Hume2** [comment]
Done. Feel free to test or contribute.

**Comment by Savsish** [comment]
Please include this in 0.4.0! Supertux Milestone 2 would not seem complete without a decent level editor. ;)

**Comment by Hume2** [comment]
It would be nice, but I can't, because there are still several urgent bugs those I can't fix.

**Comment by brmbrmcar** [comment]
0.banana.0

**Comment by Karkus476** [comment]
The ex-game level editor is developed separately. Therefore, the stability of 0.4.0 is not affected by the editor's stability. This pull request however, is a huge change, and there is lots to be discussed before it is even merged, let alone considered stable. If we want to finish 0.4.0 by December then this just cannot be included. Hopefully the external editor I am working on will be stable some time in the future.

**Comment by Hume2** [comment]
I didn't have time to finish this (too much writing :D), it's still not merged, but now everyone can contribute at least.

**Comment by Karkus476** [comment]
@Hume2 You need to close this pull request and pull from SuperTux:editor to SuperTux:master

**Comment by Hume2** [comment]
Redirect discussion to #269

**Pull request closed without merging**
