### PR TITLE
Add invincibleone() function to Console.

### PR DESCRIPTION
**Pull request by brmbrmcar**
invincible() ran it an infinite number of times. This does it once.

### CODE REVIEW

**Comment by Hume2** [comment]
It's good. May I just ask why is it called invincibleone and not make_invincible?

**Comment by brmbrmcar** [comment]
To make it more like the other script. I could make that change though if you think it would be better.

**Comment by Hume2** [comment]
You don't have to change it. I was just wonder.
Anyway, when you make a commit that doesn't change the source code, please put "[ci skip]" to the commit message. This will skip the Travis CI build.

**Comment by tobbi** [comment]
I don't like the name. Why not change the parameters on the invincible function? Or add a paremeter (bool once = false) but can be overridden.

**Comment by tobbi** [comment]
I believe invincible(bool continuous = true) would be good.  If continuous is set to false, this translates to only one invincible thing.

**Comment by brmbrmcar** [comment]
But there is no script for invincible().

**Comment by brmbrmcar** [comment]
But bool continuous =true would work.

**Comment by brmbrmcar** [comment]
Your idea does not work, unfortunately.

**Comment by Karkus476** [comment]
A script which gives tux invincibility and another which toggles it

**Comment by brmbrmcar** [comment]
Error with updating it.

**Comment by brmbrmcar** [comment]
How to fix?

**Comment by maxteufel** [comment]
ref: #220

**Pull request closed without merging**
