### PR TITLE
Coins are now musical coins

### PR DESCRIPTION
**Pull request by Savsish**
The coins now change pitch of the sound depending on how you collect them by going up or down the tiles.

### CODE REVIEW

**Comment by tobbi** [comment]
https://travis-ci.org/SuperTux/supertux/jobs/128501539#L1453

**Comment by Savsish** [comment]
I don't know how to fix the code to get working with last git changes. Advice?

**Comment by tobbi** [comment]
This looks good, the curl error on AppVeyor build seems unrelated. Okay, @SuperTux/developers what do you think?

**Comment by maxteufel** [comment]
Squash the commits?

**Comment by Hume2** [comment]
Yeah, squash the commits, please.

**Comment by Hume2** [comment]
Closing for lack of support. If you want to continue in your job, tell me to reopen this.

**Pull request closed without merging**
