### PR TITLE
Fix reset point being reactivated after restarting level

### LINKED ISSUE #338: Active checkpoint is not reset after restarting level
In SuperTux 0.4.0, if you go to the checkpoint of any level, then restart the level (Esc → restart level), then the “checkpoint bell” is still “ringing” when you pass it another time. So you can't activate it, and if you die, you have to start from the beginning rather than from the checkpoint.

### PR DESCRIPTION
**Pull request by MiroslavR**
Fixes #338.

### CODE REVIEW

**Comment by tobbi** [comment]
While you're at it, please add a space before the opening {

**Comment by MiroslavR** [comment]
> While you're at it, please add a space before the opening {

Done.

**Comment by Hume2** [comment]
Merged. Thank you for fixing that bug. :+1:

**Comment by tobbi** [comment]
Hey, MiroslavR, I like your contributions. If you feel like having a quick chat, drop by in our #supertux channel on Freenode.

**Pull request closed without merging**
