### PR TITLE
Updated Badguys (WIP)

### PR DESCRIPTION
**Pull request by Alzter**
8 frame walk cycles for Snowball and Iceblock as well as stronger outlines to make them more distinguishable.

Previews:
SnowballwalkWIP3 Iceblockwalk2

TO-DO: Enemy variants

### CODE REVIEW

**Comment by Nickeros** [comment]
The animation did alzter i like it drawing

**Comment by busybody42** [comment]
At least just keep the old sprites in some legacy folder, in case somebody prefers the old sprites in a custom level...

**Comment by busybody42** [comment]
and maybe you could add BOTH of the new spiky walk cycles, and maybe even alternate between using the 2 animations in game?

**Comment by Alzter** [comment]
> and maybe you could add BOTH of the new spiky walk cycles, and maybe even alternate between using the 2 animations in game?

There's only one new spiky walk cycle?

**Comment by busybody42** [comment]
I thought it was BETTER than the 2nd one...

**Comment by serano01** [comment]
@Alzter: Would it be okay for you when I merge this first batch of reworked badguys to master?

**Comment by Rusty-Box** [comment]
> @Alzter: Would it be okay for you when I merge this first batch of reworked badguys to master?

@serano01 The spiky animation has too much of a turn in its movement which makes it look really weird. I would like to have this addressed before merging this.

**Comment by busybody42** [comment]
@Rusty-Box, that's exactly what I was thinking!

**Comment by Alzter** [comment]
Wow, it's merged? Awesome!

Enemies I think need changing some time in the future:
Jumpy: The metal texture has too much contrast and doesn't look right
Spiky: Same problem as jumpy + his walk looks off
Flying snowball: Same problem as jumpy, he looks too squashed also for lack of a better term

Other enemies to redo in future: Crystallo, Walking Leaf, etc

**Comment by Rusty-Box** [comment]
@Alzter I personally think in their sleeping sprite spiky's eyes should not be visible. Maybe it is just me but the way it looks here looks really weird

**Comment by serano01** [comment]
Note that the old spiky-sprites are still in use, as not everyone was satisfied with them. But for the other badguys it was about time, I thought.

**Pull request merged**
