### PR TITLE
Improve Tux' sliding behavior

### LINKED ISSUE #2723: Tux sliding on belly sprite should be orientated to fit the angle of the slope they're sliding down
13 seconds into the SuperTux: Development Summary of 2023! we see Tux stay perfectly horizontal on a slope while sliding rather than diagonally.

### LINKED ISSUE #2785: Revert or greatly improve rotating Tux on slopes
This additions should have never been merged in the state it was in. I recommend reverting entirely if a fix is not considered in a timely manner unless someone is willing to highly improve it ASAP!

**Some major issues I have spotted:**
- It worsens the slide jump animation by adding a rotation to it for no reason
- The rotating is awkward and clunky with no smooth transition, whatsoever

### PR DESCRIPTION
**Pull request by Brockengespenst**
* Do smooth transition on slope angle change
* Continue to use slidejump animation when releasing jump button during slidejump
* Fix animation glitches in transition from crawling to sliding
* Add possibility to pause/resume animations and apply this for crawling and climbing when not moving

Fixes #2785
Fixes #2723

### CODE REVIEW

**Comment by Rusty-Box** [comment]
This already feel much, much better! Thank you. Sorry again if I came off as rude in my issue. I was just a bit upset with how fast this got merge without proper testing by the team. Luckily you worked on a fix pretty quickly! Thanks again :)

**Comment by mrkubax10** [comment]
> I was just a bit upset with how fast this got merge without proper testing by the team.

Yes, I admit that this was my fault because it was me who merged it too quickly. Next time I won't do that.

**Comment by Brockengespenst** [comment]
> This already feel much, much better! Thank you. Sorry again if I came off as rude in my issue. I was just a bit upset with how fast this got merge without proper testing by the team. Luckily you worked on a fix pretty quickly! Thanks again :)

No problem. Luckily this motivated me more than it frustrated me. ;-)

**Comment by Brockengespenst** [comment]
I added some changes to improve the transition from crawling to sliding and vice versa, this looks much smoother now.
Additionally when not moving left or right while crawling, the duck animation will not be displayed, but the crawling animation will just be stopped. If starting to crawl again, the crawl animation is continued. This feels more natural for me as Tux stays in the crawl position as long as the down button is pressed.

**Comment by Rusty-Box** [comment]
This does look pretty good - one question though: You think you could make it pause on the last frame shown? RIght now Tux always goes to (I presume) the first frame of his crawling animation. It would give it an even more natural look, if it would pause the animation at the frame it was last. If that isn't too much of a hassle do - something the climbing animation would also greatly benefit from.

Otherwise this is great! 👍

**Comment by Rusty-Box** [comment]
I do think I found another bug! If you die when the sprite is rotated, Tux's death animation will also be rotated.

**Comment by Rusty-Box** [comment]
There this is one issue that it causes right now. After you an animation got paused during crawling or climbing and you proceed to do something else Tux will now be forever stuck on the first frame of each animation for the rest of the level.

**Comment by Brockengespenst** [comment]
Uh, sorry. I guess it was a bit too late yesterday. Now the animation is automatically continued when another action is set. I guess this is the most intuitive behavior and fixes the issue.

**Comment by RustoMCSpit** [comment]
there should also be particle effects depending on the environment. if theyre in snow and going fast, snow should come off their trail

**Comment by RustoMCSpit** [comment]
is there any way this can be incorporated into level design where tux has to gain momentum with slopes

**Review by Rusty-Box — APPROVED** [review]
Alright. All seems to be good now! :)

**Review by mrkubax10 — APPROVED** [review]

**Review by MatusGuy — APPROVED** [review]

**Comment by RustoMCSpit** [comment]
when will the flatpak see this change?

**Comment by tobbi** [comment]
I checked on flathub and saw that there's only released versions on there, so most likely later this year when we release a stable version.

You can get nightly builds from http://download.supertux.org

**Comment by RustoMCSpit** [comment]
> I checked on flathub and saw that there's only released versions on there, so most likely later this year when we release a stable version.
> 
> You can get nightly builds from http://download.supertux.org

any reason for that? is the build unstable??

**Pull request merged**
