### PR TITLE
Optimize pngs using matthiaskrgr/woptipng

### PR DESCRIPTION
**Pull request by matthiaskrgr**
195 of 1992 files optimized, 8358891 bytes reduced to 6375354 bytes; -1983537 bytes, -23.72%
Optimization threshold was 10% (optimizations below 10% were discarded)

Script uses imagemagick, advdef and optipng.

### CODE REVIEW

**Comment by maxteufel** [comment]
Also see #216

**Comment by matthiaskrgr** [comment]
Note that optipng -np -nc avoids reduction to palette color space.

You can find palette images in the branch via
````
git diff  --name-only master | grep "\.png$" | xargs identify -verbose | grep "^Image\|PLTE" 
````
There were 4 palette images
````
data/images/tiles/auxiliary/black.png
data/images/objects/lightmap_light/lightmap_light-large.png
data/images/engine/console2.png
data/images/background/fog.png
````
however all of these were already palette in the first place on master branch so I think there won't be a problem with these.

**Comment by maxteufel** [comment]
I think a compression script should be rather run when packaging distributed versions. As far as the git repository is concerned, this will not bring any advantage, it will only increase its size.

**Comment by matthiaskrgr** [comment]
It will reduce size for final releases and shallow clones.
If a package maintainer runs image compression, bugs (like the sdl palette problem) might stay unnoticed until the final package is shipped to the user.

**Comment by ildar** [comment]
Excuse me, IMHO optimizing for 2 megabytes is for nothing if it doesn't fix
any issues. And AFAIU it doesn't indeed.

**Comment by matthiaskrgr** [comment]
I was talking to @tobbi on irc and he wanted me to make this pull request.

**Comment by tobbi** [comment]
Bbut....doesn't anyone think of the users who still have dialup?

**Comment by maxteufel** [comment]
I don't think we need this for now. Please bring it up here if anyone really thinks this is necessary.

**Pull request closed without merging**
