### PR TITLE
Add help() function to Console

### PR DESCRIPTION
**Pull request by brmbrmcar**
The content could probably be improved.

### CODE REVIEW

**Comment by Hume2** [comment]
It's good, but the help function usually writes a list of all commands those can be used and says what a specific command does.

**Comment by brmbrmcar** [comment]
I will modify.

**Comment by brmbrmcar** [comment]
I believe the console now needs some sort of scrolling thing.

**Comment by maxteufel** [comment]
People who would need this aren't supposed to use the console.

Furthermore, that is not a very complete overview of commands - there's quite a bunch of classes with methods you can find instances of in the console.

**Comment by brmbrmcar** [comment]
> People who would need this aren't supposed to use the console.

I feel that is not true. Most people actually use it to cheat, or try something out. I did it for a long time, not knowing what a lot of the tricks were.

> that is not a very complete overview of commands

I only included working commands, and ones defined in console.nut.

**Comment by maxteufel** [comment]
> Most people actually use it to cheat,

Cheat menu exists for that purpose.

Console is mostly for level designers and developers, both of whom should be able to read the relevant documentation in [the scripting reference](https://github.com/SuperTux/wiki/blob/mediawiki/Scripting_reference.mw) or in the code.

> I only included working commands, and ones defined in console.nut.

`console.nut` only defines some functions that make access to others easier. What also works are functions like `println()`, but there's also several instances of classes in the console with callable methods (see scripting reference linked above) - such as an instance of `Sector` called `sector.settings`, an instance of `Player` called `sector.Tux`, and some more.

**Comment by brmbrmcar** [comment]
> console.nut only defines some functions that make access to others easier. What also works are functions like println(), but there's also several instances of classes in the console with callable methods (see scripting reference linked above) - such as an instance of Sector called sector.settings, an instance of Player called sector.Tux, and some more.

Yes, but if you happened to need the help() you would only need the preset commands anyway, most likely.

**Comment by maxteufel** [comment]
Yeah, but if you need `help()` you don't need the console but the cheat menu.

**Comment by maxteufel** [comment]
In fact, we should focus on making high quality levels that people will be able to play. Even the cheat menu isn't designed for end users. I've yet to see a commercial game saying **CHEAT HERE**.

**Comment by brmbrmcar** [comment]
I guess so... maybe when running the Console on the first run it should be stating that.

**Pull request closed without merging**
