### PR TITLE
Add in extra character...

### PR DESCRIPTION
**Pull request by busybody42**
https://github.com/SuperTux/supertux/pull/765
This had a missing character...
I've added it in...
(THIS IS SUPPOSED TO REPLACE THE WHITE-BIG AND SHADOW-BIG IMAGES)
white-big
shadow-big

(sorry, this was as close as I could get to finding a font pull request)

### CODE REVIEW

**Comment by tobbi** [comment]
NIce try ;)

**Comment by busybody42** [comment]
...Why are the other commits even there?

**Comment by busybody42** [comment]
@tobbi, ok, seriously, how do I make a pull request that modifies the file?
I wanna make a commit to add in the extra character...
not any of these random 33 ones that I don't want!

**Comment by tobbi** [comment]
How do you usually do it?

**Comment by busybody42** [comment]
(This is the first time I ever tried a pull request)
(Let me try it again...)

**Comment by busybody42** [comment]
@tobbi 
feel free if you want to reopen it, though

**Pull request closed without merging**
