### PR TITLE
Icecrusher: Do not stop rising when there's an obstacle

### LINKED ISSUE #431: Icecrusher Bug
SuperTux 0.4.0
Windows 7 64-bit

Once the icecrusher hits the ground throwing a portable rock on the icecrusher and after removing it the icecrusher doesn’t go back up and return to normal behavior.  
The icecrusher should go back up and return to normal behavior after removing the portable rock on top of it. (By portable rock I mean those blocks in 'Tux The Builder' level.)

### PR DESCRIPTION
**Pull request by Hume2**
fixes #431

### CODE REVIEW

**Comment by maxteufel** [comment]
Can you document this in `docs/levelguidelines.txt` and other appropriate places?

**Comment by Hume2** [comment]
@maxteufel Done.

**Comment by Hume2** [comment]
Oops, not really.

**Comment by maxteufel** [comment]
Looks good to merge.

**Pull request merged**
