### PR TITLE
Create info_block.sprite

### PR DESCRIPTION
**Pull request by brmbrmcar**
Makes this thing usable.

### CODE REVIEW

**Comment by Hume2** [comment]
Do we still need that thing? Can't we just delete that?

**Comment by brmbrmcar** [comment]
Well, it was added for something...

**Comment by tobbi** [comment]
Are we talking about the telephone? This is ugly, IMO.

**Comment by brmbrmcar** [comment]
I like it.

**Comment by Hume2** [comment]
Yes, this is the telephone.

**Comment by Hume2** [comment]
Refused.

**Comment by brmbrmcar** [comment]
Then it should be deleted as soon as possible.

**Comment by Hume2** [comment]
Now it's deleted.

**Pull request closed without merging**
