### PR TITLE
Remove extension from icon name in desktop file

### PR DESCRIPTION
**Pull request by volkov0aa**
According to Icon Theme Specification
https://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html
extensions should not be used in icon names (LookupIcon algorithm).

### CODE REVIEW

**Comment by tobbi** [comment]
@maxteufel @maths22 I assume this is fairly trivial. I just wanted your final review on this, since you know that stuff better than me.

**Comment by maxteufel** [comment]
I *think* this should be okay, assuming you have tested it, @volkov0aa.

**Comment by volkov0aa** [comment]
Try 'grep --color Icon /usr/share/applications/*' on your system. Almost all desktop files contain icon names without extensions.

**Comment by tobbi** [comment]
I reviewed the spec and its example and this seems to be the way to go.

**Pull request merged**
