### PR TITLE
Change all "normal" actions to "default"

### PR DESCRIPTION
**Pull request by MatusGuy**
This will absolutely remove all sprite file inconsistencies between "normal" and "default". Seriously, what were they thinking!

Now that all files are consistent there should be no more weird cases with objects showing wrong actions or giving cryptic warnings.

Testers: Please test badguys like granito, goldbomb, etc. thoroughly

### CODE REVIEW

**Review by weluvgoatz — APPROVED** [review]
Tested, reviewed code, works good and fine.

**Comment by MatusGuy** [comment]
Fixed that just now

**Comment by weluvgoatz** [comment]
I just noticed that the bumper has the same issue.

**Comment by MatusGuy** [comment]
> I just noticed that the bumper has the same issue.

Can't reproduce this issue

**Comment by Rusty-Box** [comment]
I can confirm the bumper issue. They work upon first time interacting with them but any subsequent time they will be stuck. Also bumpers facing left won't do so unless interacted with once.

**Review by swagtoy — APPROVED** [review]
Everything in this change seems consistent. Code looks correct.

**Pull request merged**
