### PR TITLE
Use correct stats in LevelIntro

### PR DESCRIPTION
**Pull request by Cleverking2003**

### CODE REVIEW

**Comment by tobbi** [comment]
Can you please squash your commits into one?

**Comment by Cleverking2003** [comment]
Fixed it

**Comment by maxteufel** [comment]
By pushing that merge commit you rather unfixed my fix from this morning. I should have written about it here.

Anyway, can you please fix the compilation issues with Clang?

**Comment by Cleverking2003** [comment]
Why does this happen?

**Comment by Cleverking2003** [comment]
Now just gonna wait for approving review

**Comment by tobbi** [comment]
Your wish may be granted!

**Comment by Grumbel** [comment]
This fix crashes the game when a level is started from command line:

```
$ gdb --args build/supertux2  --renderer sdl data/levels/halloween2014/halloween1.stl 
[...]
Thread 1 "supertux2" received signal SIGSEGV, Segmentation fault.
0x000055555599d9fd in std::max<int> (__a=<error reading variable>, __b=@0x7fffffffca50: 0) at /usr/include/c++/8/bits/stl_algobase.h:224
224	      if (__a < __b)
(gdb) where
#0  0x000055555599d9fd in std::max<int> (__a=<error reading variable>, __b=@0x7fffffffca50: 0) at /usr/include/c++/8/bits/stl_algobase.h:224
#1  0x0000555555a8daba in LevelIntro::draw (this=0x555556860f60, compositor=...) at /home/ingo/projects/supertux/trunk/supertux/src/supertux/levelintro.cpp:168
#2  0x0000555555970e5d in ScreenManager::draw (this=0x7fffffffce90, compositor=...) at /home/ingo/projects/supertux/trunk/supertux/src/supertux/screen_manager.cpp:158
#3  0x0000555555971a38 in ScreenManager::run (this=0x7fffffffce90) at /home/ingo/projects/supertux/trunk/supertux/src/supertux/screen_manager.cpp:423
#4  0x0000555555960c9f in Main::launch_game (this=0x7fffffffd5b7, args=...) at /home/ingo/projects/supertux/trunk/supertux/src/supertux/main.cpp:468
#5  0x0000555555961411 in Main::run (this=0x7fffffffd5b7, argc=4, argv=0x7fffffffd6a8) at /home/ingo/projects/supertux/trunk/supertux/src/supertux/main.cpp:538
#6  0x000055555595f68c in main (argc=4, argv=0x7fffffffd6a8) at /home/ingo/projects/supertux/trunk/supertux/src/main.cpp:23

```

**Comment by Grumbel** [comment]
Fixed in 518e9a862

**Pull request merged**
