### PR TITLE
Levelintro Fixes- issue #127

### PR DESCRIPTION
**Pull request by Karkus476**
Fixes SuperTux/supertux#127
I've hopefully also fixed the warnings.
Changes (referring to levelintro):
-  Tux animation is appropriate to the player bonus
-  When tux jumps the jump animation is shown

Any other changes to the levelintro screen?

### CODE REVIEW

**Comment by maxteufel** [comment]
Could you [squash these commits](https://help.github.com/articles/using-git-rebase/) and also change the commit messages (it's fine to add a reference to an issue/other pull request but when someone's looking at the git log they won't know what issue #xyz is).

**Comment by Karkus476** [comment]
Thanks, I'll get to it

**Comment by tobbi** [comment]
Please rebase with the latest code from master.

**Comment by Karkus476** [comment]
I don't understand what you mean... do you mean that my pull request is outdated? You can tell I'm new, sorry.

**Comment by tobbi** [comment]
What I mean is that I can see one of my commits in there (see how it says two commits?).

**Comment by tobbi** [comment]
Actually, doesn't matter. I will cherry-pick the relevant commit.

**Comment by Karkus476** [comment]
Right.

**Comment by Karkus476** [comment]
@tobbi I think you only took the first commit (therefore you missed the jumping animation) was that intentional?

**Comment by tobbi** [comment]
Do you have a way to include the second commit that you apparently left out?

**Comment by Karkus476** [comment]
Another pull request? SuperTux/supertux/pull/132

**Pull request closed without merging**
