### PR TITLE
Add "Others" category with tiles that are not in any other category.

### PR DESCRIPTION
**Pull request by tobbi**
Problem with this is that it shows a lot of empty tiles because we have IDs assigned to empty tiles. We should fix that.

### CODE REVIEW

**Comment by tobbi** [comment]
I changed the code slightly to give me the tile IDs of those blank tiles. Resulting screenshot:
https://www.dropbox.com/s/axqcroq4x306fjv/Screenshot%202017-07-20%2000.21.39.png?dl=0

**Comment by maxteufel** [comment]
@tobbi That's only for the new "Others" category then? If so, that seems like a good idea.

For what it's worth, we could put this whole "Others" category behind the developer toggle.

**Comment by tobbi** [comment]
I didn't change *this* code. This was only locally.

**Comment by maxteufel** [comment]
I say that if that only applies to the Others category, then it would be a good idea to push it to this pull request.

Moreover, we should put the entire Others category behind the developers toggle.

**Comment by tobbi** [comment]
One more thing: We should check whether certain levels use the duplicate IDs and change them to the other ones.

**Comment by tobbi** [comment]
I can't remember whether this still needs work or not. Any ideas?

**Pull request merged**
