### PR TITLE
Do not let Tux shoot when ducking

### PR DESCRIPTION
**Pull request by n0toose**

### CODE REVIEW

**Comment by Frostwithasideofsalt** [comment]
Personally i would be against this being merged, as tux being able to shoot when ducking isn't really an issue.

**Comment by n0toose** [comment]
I don't really have any other proper arguments for it other than vibes, the lack of an animation that makes this feature ultimately feel clunky and naming Mario games as an example where you can't do that.

**Comment by tylerandari13** [comment]
> I don't really have any other proper arguments for it other than vibes, the lack of an animation that makes this feature ultimately feel clunky and naming Mario games as an example where you can't do that.

To be fair theres no animation for him throwing a fireball when standing either.

**Comment by n0toose** [comment]
> To be fair theres no animation for him throwing a fireball when standing either.

yeah, uh, I didn't think about that, but it looks like the fireball is spawning out of thin air! Would you be able to throw a bowling ball like that? 🎳

**Comment by MatusGuy** [comment]
It's not a bad nerf to the fire flower.

**Comment by Vankata453** [comment]
Tux shooting while ducked is essential for passing certain sections in levels. For example, it allows shooting fireballs more precisely, which makes some close-up one-tile pathway sections with ice passable.

> preparing for a backflip also comes with the tradeoff that you are leaving yourself somewhat exposed, and throwing a fireball feels like cheating your way away from that danger.

I don't agree, it's not really cheating the way through danger. In fact, if a player were to backflip/slide and danger immediately approached, I'd be impressed from it being pulled off, considering the danger should have come pretty fast towards Tux (otherwise the player would've already eliminated it before preparing to backflip/slide), and the player would have been focused on performing a different action in the meantime.

Personally I don't see why this mechanic should be taken away from the player. Additionally, before sliding was implemented, Tux was able to do the so-called "Duck Jumping" when ducked, which I'd personally love to see come back.

**Comment by n0toose** [comment]
You have a point, I think this should be closed.

**Pull request closed without merging**
