### PR TITLE
Remap new tiles to compatible mapping

### LINKED ISSUE #2306: Recent tileset changes broken
The tileset changes from 2022-10-06 are seemingly broken:

screenshot cleaned

### PR DESCRIPTION
**Pull request by Semphriss**
image

Fixes #2306

The new tiles have been remapped according to their old IDs.

TODO:
- [x] Remap forest tiles
- [x] Remap ghost forest tiles

### CODE REVIEW

**Comment by Semphriss** [comment]
Note: The PR duplicates the whole images folder across the commit history. When (or before) merging, please delete `data/images_old/` and squash to remove it from the git history.

**Comment by tulpenkiste** [comment]
Did some performance tests between this and nightly 750:
- SDL 2.0.10 with Draw Redundant Frames on (latest nightly)
  - 500fps average
- SDL 2.0.10 with Draw Redundant Frames on (this pr)
  - 450fps average
- OpenGL 3.3 with Draw Redundant Frames on and vsync off (latest nightly)
  - 400fps average
- OpenGL 3.3 with Draw Redundant Frames on and vsync off (this pr)
  - 400fps average
  
  Vankata wondered if it's due to tiles being re-added.

**Comment by Semphriss** [comment]
I haven't succeeded reproducing this, so as we discussed, if you could try with a profiler and send your results, it would help me.

**Comment by Vankata453** [comment]
Closing due to the merge of #2671.

**Pull request closed without merging**
