### PR TITLE
Deletion of a reference to an old (and deleted) file about level editor

### PR DESCRIPTION
**Pull request by hogren**

### CODE REVIEW

**Review by Semphriss — APPROVED** [review]

**Comment by Ordoviz** [comment]
If you are wondering, that information is now on the [wiki](https://github.com/SuperTux/supertux/wiki/Leveldesign).

**Comment by tobbi** [comment]
@hogren If you could change the URI to point to the wiki, it'd be much appreciated.

**Comment by hogren** [comment]
@tobbi I made that in [my first pull request](https://github.com/SuperTux/supertux/pull/1644). But @Semphriss said that Wiki is already accessible.
I don't want to offend anybody.

**Comment by tobbi** [comment]
Alright, merged this.

**Pull request merged**
