### PR TITLE
Keep InfoBlock message inside screen

### LINKED ISSUE #1229: Help block text might get cut off
**SuperTux version:** 0.6.1 beta 1
**System information:** GNU/Linux

##### Expected behavior
All help block texts are fully visible on the screen.

##### Actual behavior
In the first Forest level, the help block text is not completely visible on my screen (1920×1080 fullscreen).

##### Workaround
When I press "scroll up", I can see the full text. But still, that's confusing!

##### Steps to reproduce actual behavior
1. Go to the first help block in the first Forest level
2. Activate it
3. Look at the text. Is it fully visible or cut off by the screen?

### PR DESCRIPTION
**Pull request by mrkubax10**
Fixes #1229

### CODE REVIEW

**Comment by Semphriss** [comment]
Would it be feasible (and if so, a positive addition) to preemptively also constrain the left, right and bottom borders?

**Comment by mrkubax10** [comment]
Yes

**Comment by mrkubax10** [comment]
After some research: it is impossible for message to show under screen, also constrain at edges of sectors is already in game

**Review by Semphriss — APPROVED** [review]
Looks good then

**Comment by Zwatotem** [comment]
> After some research: it is impossible for message to show under screen, also constraining at edges of sectors is already in game

If this holds true than looks good to me as well.

**Pull request merged**
