### PR TITLE
MusicalCoin

### PR DESCRIPTION
**Pull request by SuperTuxFan**
I was requested to make a pull request to make a musical coin, and I did! Hope you guys like it!

### CODE REVIEW

**Comment by maxteufel** [comment]
Uhhh... what? This code won't compile. And it's copied from <https://github.com/SuperTux/supertux/blob/master/src/object/coin.cpp#L112-L178> anyway.

**Comment by SuperTuxFan** [comment]
Oh.

**Comment by maxteufel** [comment]
Some questions…

1. who requested you to make a pull request?
2. where from is that code?
3. you don't seem to understand what you did here. what made you think you would?

…I'm quite puzzled about this pull request.

**Comment by SuperTuxFan** [comment]
1. Tobbi asked me to make a pull request.

2. The code came from here: https://forum.freegamedev.net/viewtopic.php?f=68&t=6915

**Comment by tobbi** [comment]
When I asked you to make a pull request, the code above was commented out in our repo. This has changed with dac13b2, which was committed after I told you to make the change. Anyway, this was superseded by dac13b2, therefore. closing.

**Pull request closed without merging**
