### PR TITLE
(WIP) Getting growth powerup no longer makes Tux fall off ladder

### LINKED ISSUE #1074: Getting an egg while climbing a ladder causes falling off
**SuperTux version:** 0.6.0
**System information:** NixOS 18.09, Linux 4.14.98

##### Expected behavior

When climbing a ladder and touching an egg, Tux grows and continues climbing.

##### Actual behavior

When climbing a ladder and touching an egg, Tux grows and falls off the ladder.

##### Steps to reproduce actual behavior

Climb a ladder and get hit by an egg. This can be done in "End of the tunnel", a bit after the checkpoint.

### PR DESCRIPTION
**Pull request by martinvanzijl**
Fixes #1074. Enables Tux to grow while he is climbing a ladder. Video demo below:

grow-on-ladder-demo

**Still to do**:

- [ ] Create a better "growing on ladder" sprite.
- [ ] If possible, make Tux look less awkward when climbing up/down as he is growing.

### CODE REVIEW

**Comment by martinvanzijl** [comment]
Is anyone willing to make a proper "growing on ladder" sprite? The current one is just a placeholder made by stretching/squashing the climbing sprite in GIMP.

**Comment by tobbi** [comment]
> Is anyone willing to make a proper "growing on ladder" sprite? The current one is just a placeholder made by stretching/squashing the climbing sprite in GIMP.

@SuperTux/graphics-designers  ^^

**Comment by serano01** [comment]
I honestly think it looks pretty good, not perfect, but still well enough. Because, how often does it occur that you're on a ladder while a egg appears?

**Comment by martinvanzijl** [comment]
Why thank you, @serano01. I guess it does not happen often, so it is OK if it's not perfect.

Tux still looks a little awkward when moving up/down as he is growing - like he is sliding. See below:

grow-while-climb-demo

What do you think, can we merge as is?

**Comment by serano01** [comment]
If no one says otherwise, yes.

**Comment by tobbi** [comment]
I agree as well. Let's merge it, this is very good! :)

**Pull request merged**
