### PR TITLE
Coin: Change the sound pitch depending on its y-pos

### PR DESCRIPTION
**Pull request by Hume2**
I think, this wasn't such a bad idea. It was already there, just commented.

### CODE REVIEW

**Comment by maxteufel** [comment]
Does this also affect coins in boxes?

**Comment by Hume2** [comment]
No, it doesn't.

**Comment by maxteufel** [comment]
Can that be changed as well?

**Comment by Hume2** [comment]
This would be a bit more difficult.

**Comment by maxteufel** [comment]
Looks good to merge. What I suggested can be added later. But do we want to merge this for 0.5? Isn't it 0.6?

**Pull request merged**
