### PR TITLE
New Snow Tileset

### PR DESCRIPTION
**Pull request by Alzter**
I added the new snow tiles into the game.

### CODE REVIEW

**Comment by serano01** [comment]
While I like them visually, I think, like RustyBox said, that these tiles should replace the old ones, not going alongside with the old stuff.

**Comment by weluvgoatz** [comment]
Please have the snow top thing overlap a little bit, you don't seem to
understand entities start floating when it doesn't overlap.

**Comment by Alzter** [comment]
Well I can change it but that'd mean going over all the snow tiles with snow om them and repositioning the snow. I'll do it soon-ish.

**Comment by busybody42** [comment]
blergh... The snow on the top is too big...

**Comment by weluvgoatz** [comment]
These tiles were implemented properly in a recent commit, thanks Alzter. :-)

**Pull request closed without merging**
