### PR TITLE
Fix explosion sprite FPS.

### PR DESCRIPTION
**Pull request by GreenMouseFan**
A small pull request fixing explosion sprite framerate. Now it should explode for approx 1 second.

### CODE REVIEW

**Comment by weluvgoatz** [comment]
What? There is literally nothing wrong with it, don't know why this was made...

**Comment by GreenMouseFan** [comment]
There was a change to FPS of the animation but they do it to the wrong sprite and explosions lasted for less than a second as a result. I think this fix will allow more time for explosions and making the game easier.

**Comment by Semphriss** [comment]
At 8 FPS, the animation is too jerky and irregular. It cannot fit with its graphical surroundings.

I haven't seen any other complaints about the bomb so far, but if we are to adjust it, we should reduce the cooldown time rather than the FPS. I have an easier time understanding that the bomb's explosion shouldn't hurt after 0.75 seconds than that poor graphical performance is worth the shot.

**Comment by GreenMouseFan** [comment]
Maybe 12 fps, cuz there are now 12 frames of animation?

**Comment by tobbi** [comment]
@SuperTux/graphics-designers I need your input on this one.

**Comment by weluvgoatz** [comment]
I would prefer closing it.

**Comment by tobbi** [comment]
Can I get the two sprites side-by-side with the different fps'es?

**Pull request closed without merging**
