### PR TITLE
Adjust mushroom decals

### PR DESCRIPTION
**Pull request by serano01**
Made the images significant smaller and better to use.

### CODE REVIEW

**Comment by Semphriss** [comment]
Do the ghost forest levels need to be adjusted? <sub>(If yes, does it matter?)</sub>

**Comment by serano01** [comment]
I don't think so. But a follow-up PR is coming anyway (the user bar from discord is working on it).

**Comment by Narre** [comment]
Well, you removed not only the transparent bits to the right and bottom, but also left and top, which means the existing decals will be off by a few pixels, and bar's PR will probably be done before this is merged, so I'd say adjustments will be needed.

**Comment by weluvgoatz** [comment]
I played around with it, and it doesn't seem like these changes affect the placement of the decals in the levels.  If they somehow do, I'll fix up the levels.

**Pull request merged**
