### PR TITLE
Castle Tile Improvements

### PR DESCRIPTION
**Pull request by jonfx1007**
Fixes graphical and tiling errors for the brown castle and snowcastle tilesets, as well as adding some new tiles to the brown castle, snowcastle, and grey castle tilesets.

Closes SuperTux/data#22.

Also addresses Projects/Tileset Improvements/Other level tiles/Fix tiling for snow and brown castle.

### CODE REVIEW

**Comment by jonfx1007** [comment]
Wanted to submit this earlier, as I had the tiles mostly ready, but school and other things got in the way.

**Comment by jonfx1007** [comment]
By the way, is there a proper way to reference an issue in another repository? The way I tried it didn't seem to work correctly.

**Comment by maxteufel** [comment]
> Wanted to submit this earlier, as I had the tiles mostly ready, but school and other things got in the way.

Don't worry. Your work is really appreciated.

> By the way, is there a proper way to reference an issue in another repository? The way I tried it didn't seem to work correctly.

It's closes user/repo#issuenumber. That's documented somewhere in GitHub's help documentation.

It looks great, I will test this in the near future. If everything's okay, it will be merged.

**Comment by maxteufel** [comment]
@jonfx1007 Where did the right part of `data/images/tiles/castle/brown.png` go?

**Pull request merged**
