### PR TITLE
Icy Island Tweaks

### PR DESCRIPTION
**Pull request by weluvgoatz**
This PR has done the following:

- Fix gradients
- Fix naming conventions
- Update the worldmap
- Update 2 out of the 3 cutscenes to make more sense
- Fix some enemy crowding and bad jumps
- Fix some other miscellaneous changes (not being able to see yeti icicles, vibe killer in castle and wrong egg infoblock image in level 1)

Please look at it and consider it, @Rusty-Box and @serano01

### CODE REVIEW

**Comment by serano01** [comment]
Good PR, but you messed up the text in castle_cutscene.stl: "Unsure about where Nolok was doing to her,\\nTux became worried about his beloved Penny.\" Please change.

**Comment by weluvgoatz** [comment]
> Good PR, but you messed up the text in castle_cutscene.stl: "Unsure about where Nolok was doing to her,\nTux became worried about his beloved Penny." Please change.

fixed

**Comment by tobbi** [comment]
Can this be merged?

**Comment by serano01** [comment]
I'd say so.

**Pull request merged**
