### PR TITLE
[Heavily WIP] SQRat

### PR DESCRIPTION
**Pull request by tobbi**
This is, as the title says, heavily work in progress. Currently, the following works:

Calling functions of objects that have them exposed (currently: AmbientSound and Player).

For every object there is, we create a class type sqratclass_ + <name of the object> and an instance type: sqratinstance_ + <name of the object>. I know this is totally stupid, since we should create just one class type and then instances of it when the objects are created actually, but who cares. I'll fix it later, probably.

So, for example for the menu level, you can do:
`
sqratinstance_Tux.deactivate();
`

- [ ] Get sqratthread to work with internal scheduler
- [ ] Don't pass VM to each function (use Sqrat::DefaultVM() instead)
- [ ] Expose color constants to squirrel

### CODE REVIEW

**Comment by tobbi** [comment]
The Travis build fails because of warnings in SQRat code, not ours. *phew*

**Comment by maxteufel** [comment]
Reference: SuperTux/supertux#650 ("Use SQRat")

**Comment by tobbi** [comment]
Threading is bound to give us some problems. If anyone could implement the threading scripting functions, feel free. I'm struggling with them.

**Comment by tobbi** [comment]
This issue was abandoned.

**Pull request closed without merging**
