### PR TITLE
More arcade-looking Yeti death sequence, with snow flying out of Yeti

### PR DESCRIPTION
**Pull request by pelya**
Squashed commits from here: https://github.com/SuperTux/supertux/pull/520

### CODE REVIEW

**Comment by pelya** [comment]
How it looks: https://www.youtube.com/watch?v=wx8YL9YIrGk#t=41s

**Comment by maxteufel** [comment]
Cc: @SuperTux/core, @SuperTux/developers, @SuperTux/level-designers

**Comment by maxteufel** [comment]
The Windows build is currently broken because tagging the 0.5.0-rc.1 release messed up with the automatic packaging. Nothing to worry about, for you.

**Comment by Rusty-Box** [comment]
I think it looks much better than the huge yeti face.
By the way, I remember seeing graphics for a defeated yeti (or however they're called). Maybe they could be used instead of the jump graphics.

**Comment by pelya** [comment]
https://github.com/SuperTux/data/blob/master/images/creatures/yeti/iceyeti_dust0.png
https://github.com/SuperTux/data/blob/master/images/creatures/yeti/iceyeti_dust1.png
https://github.com/SuperTux/data/blob/master/images/creatures/yeti/iceyeti_dust2.png
https://github.com/SuperTux/data/blob/master/images/creatures/yeti/iceyeti_dust3.png

I'm not sure if these will look good animated, the frames are too different.

**Pull request merged**
