### PR TITLE
Nolok's Castle fix-up

### PR DESCRIPTION
**Pull request by StephenPs**
The script in Nolok's castle doesn't work properly. So now it's just an normal end sequence.

Also removed the random bell near the end of the level.

Tell me what you think about it.

### CODE REVIEW

**Comment by tobbi** [comment]
I think the 'random bell at the end of the level' is so that people get the impression that a harder path is coming up and be surprised that the level is actually over.

**Comment by weluvgoatz** [comment]
I think the end of "Castle of Nolok" is meant to have some sort of cutscene at the end, or the yeti was originally in this level.

**Comment by StephenPs** [comment]
I know that this is totally unrelated, but to give everyone a little laugh, I put the Supertux storyline though google traslate

This was the result: Tux and Benny have a wonderful trip on the ice in Antarctica. Suddenly, the creature jumped into the ice lake, there was a lightning bolt, Tux slept.

When I got home, Tex knew that Benny had disappeared. I have a message in my current place. I would say "Tex, my enemy!" "I took your sack beautifully and brought my kingdom, the road to my kingdom was scattered with my fingers, I was thinking of going back, you have no chance!

Taxis appear in the northern fort at distance and are visible. They will start traveling to save their beloved shark.

**Comment by weluvgoatz** [comment]
This made me laugh. What language did you translate from?

**Comment by StephenPs** [comment]
English to koren to Japanse to Javanese to abric and back to English, i think

**Comment by weluvgoatz** [comment]
The fingers are coming! The fingers are coming!

**Comment by Alzter** [comment]
> I think the end of "Castle of Nolok" is meant to have some sort of cutscene at the end, or the yeti was originally in this level.

http://supertux.lethargik.org/wiki/images/e/e8/Interlude01.jpg

**Comment by StephenPs** [comment]
This translation is even more funny :
There is a tux and there is a large range of picnic ice in the Antarctic. Suddenly he founded a creature of glowing ice flow and sleep Tux!

Tux woke up to ten missing. He is a witness, You will not suffer: there is a letter. "My stupid enemies!" Said the letter. "As I went down to my bronze vacuum in the server when I came back and I tried to think, did they have a chance?"

Tux I don't want to see my face at the fort. Cato the Elder, he began a spare trip.

**Comment by weluvgoatz** [comment]
Castle of Nolok was already updated by @Rusty-Box , please close.

**Pull request closed without merging**
