### PR TITLE
Upgraded several background images

### PR DESCRIPTION
**Pull request by Rusty-Box**
This PR adds brand new backgrounds for each world theme (including some of our bonus themes, i.e. Halloween and Revenge In Redmond).

---

**List of Backgrounds to be included:**

**Story Mode**
- Icy Island (Surface)
- Icy Island (Cave)
- Rooted Forest (Surface)
- Corrupted Forest (Surface)
- Castle (Ice, Forest, Corrupted)
- Antarctica
- Cave
- Haunted Island (Halloween)

### CODE REVIEW

**Comment by Grumbel** [comment]
Not seeing how the new Halloween background is any improvement. In general I find this whole art replacement a big waste of time. That effort would be better spend creating new worlds and level themes.

**Comment by Semphriss** [comment]
I would invite disagreements to be expressed with words, given that emojis leave little room for details.

**Comment by FILIPOKonGithup** [comment]
epic backgroud redesgin

**Comment by Anyone-Anonymous** [comment]
grumbel grumbles

**Comment by weluvgoatz** [comment]
There *has* been effort towards creating new worlds, as well as expanding existing ones.  For example, the ghost forest is being greatly expanded upon, and there has already been work started on tiles and BGs for Worlds 3 and 4.  I just don't think those have been posted anywhere publicly yet...

**Comment by Alasdairbugs** [comment]
> There _has_ been effort towards creating new worlds, as well as expanding existing ones. For example, the ghost forest is being greatly expanded upon, and there has already been work started on tiles and BGs for Worlds 3 and 4. I just don't think those have been posted anywhere publicly yet...

Agree with Daniel. @Grumbel  it would be nice if you joined the internal discord server where development discussions take place quite often. Perhaps if you kept in the loop you could have posted your thoughts on the graphics overhaul during more of its earlier stages.

**Comment by NickerAbanTRY23F** [comment]
how would it look good with the levels

**Comment by Rusty-Box** [comment]
I'm gonna post-poned the cave backgrounds for now so this PR can be considered complete.
More backgrounds come whenever I get to them. Will focus on the last enemy re-designs and adding new Corrupted Forest variants first and foremost

**Pull request merged**
