### PR TITLE
Add new Bonus Island 1, remove old Bonus Islands

### PR DESCRIPTION
**Pull request by weluvgoatz**
This PR, which has been a WIP for over 2 years, includes the revamp of Bonus Island 1, with levels by myself, @Frostwithasideofsalt , @Alasdairbugs , @Rusty-Box , @Sevenberry , and @bruhmoent .  The graphics also included in this PR are by @Frostwithasideofsalt.

This new version of Bonus Island 1 aims to bring the old bonus islands to a higher, more modern standard set in place by the new story mode (which has yet to be publicly available).  Whereas the story mode will be accessible to all players, the Bonus Islands aim to appeal to experienced players.  This revamp also aims to separate the Bonus Islands into the different themes of the story mode, so Bonus Island 1 has the same theme as World 1, aka the Icy Island.  So Bonus Island 1 is snow themed.

NOTE: The levels whose names end in * are WIP! This means that Nolok's Party Pit is WIP.

Further development of Bonus Island 1 should occur on this branch.

Please playtest and let us know what you think.

### CODE REVIEW

**Comment by tobbi** [comment]
For some reason, "In Flander's ice field" is really slow.

**Comment by MatusGuy** [comment]
You know what'd kick ass? If we move this branch to the main repository we can redirect users to a download.supertux.org link thanks to the new branch selector. What do you think?

**Comment by tobbi** [comment]
Can you properly rebase against master?

**Comment by weluvgoatz** [comment]
Since this is gonna be merged today, let's try to include all authors in the squashed commit, even the ones who didn't make a commit to this branch.

**Comment by NickerAban** [comment]
Letss Guu..!

**Pull request merged**
