### PR TITLE
Remove old worldmap tiles

### PR DESCRIPTION
**Pull request by Rusty-Box**
Remove the old worldmap tiles from icy island.

### CODE REVIEW

**Comment by tobbi** [comment]
I can't remember the status of this. @Rusty-Box @maxteufel Does anyone of you know more?

**Comment by busybody42** [comment]
Why? What if somebody wants to use them? Also, why would you waste something the artist(S) worked hard on?

**Comment by Rusty-Box** [comment]
@busybody42 There are two versions of the same sprites, but with a blue background which makes them pretty useless when using the animated water tiles. So if these get removed the tiles themselves still exist, but with a transparent background.

**Comment by maxteufel** [comment]
@Rusty-Box good idea in theory, but in practice the pull request how it is right *now* would break most contrib levels.

Those files from `data/images/worldmap/antarctica/`, are *all* still being the sole source of Icy Island tiles in the `worldmaps.strf` file. While they are not necessary for `ice_world.strf`, these tiles are still essential.

I think this can't really be fixed, because worldmaps using these tiles would need to be updated in any case if transparent tiles are used (since special setup is necessary with transparent tiles when you want e.g. water to show up).

**Comment by Grumbel** [comment]
.strf format supports a `(deprecated #t)` tag, that will hide tiles from the (C#) editor, but keep them available to levels already using them.

**Comment by tobbi** [comment]
@Rusty-Box Can you implement the (deprecated #t) thing so this can get merged?

**Comment by Rusty-Box** [comment]
@tobbi If you tell me how I can try doing that.

**Comment by weluvgoatz** [comment]
Is this still going to be considered?

**Pull request merged**
