### PR TITLE
Implemented Mr. Candle

### PR DESCRIPTION
**Pull request by Hume2**

### CODE REVIEW

**Comment by tobbi** [comment]
This includes files that shouldn't be there.

**Comment by brmbrmcar** [comment]
The files are already on  Supertux:master. What harm does that do?

**Comment by tobbi** [comment]
Oh, right, in that case: please rebase!

**Comment by brmbrmcar** [comment]
?

**Comment by tobbi** [comment]
I meant hume this time.

**Comment by brmbrmcar** [comment]
OK.

**Comment by Hume2** [comment]
I put those files where they belong.
Excuse me that I've accidentally removed your last commit. So if you could, don't git pull. If you have already done it, I'm willing to repair it if you tell me what was the commit about.

**Comment by brmbrmcar** [comment]
Do you mean the merge pull requests or something else?

**Pull request merged**
