### PR TITLE
Change forest world file names

### PR DESCRIPTION
**Pull request by sydneyjd**
Please test this. I hope i did it properly and didnt make any spelling mistakes. :-)

### CODE REVIEW

**Comment by Karkus476** [comment]
@sydneyjd Looks good, but there appears to be conflicts. Do you think you can fix these? Reminder for next time, also, ``[ci-skip]`` and ``fixes #175`` might have been useful in the commit messages.

**Comment by tobbi** [comment]
Altering file names will invalidate level statistics since these depend on file names...I'm inclining towards closing this.

**Comment by brmbrmcar** [comment]
You mean an upgrade from 0.3.5a?

**Comment by tobbi** [comment]
Yes.

**Comment by Karkus476** [comment]
@tobbi If you like, we can make another issue, and merge this for 0.5.0 or whatever it's called

**Comment by tobbi** [comment]
Sure, just go ahead.

**Comment by Hume2** [comment]
There are still some levels those don't have the same filename as their name, but it's obvious which level is what. Do you want to do anything with it or it can be merged?

**Comment by Karkus476** [comment]
@Hume2 it just needs to be similar

- Karkus

**Pull request merged**
