### PR TITLE
Add stacktrace info to CONTRIBUTING.md

### LINKED ISSUE #369: Documentation on debugging
Provide some links for users to guides that explain how to e.g.: get a stacktrace when the game crashes and then add that information to `CONTRIBUTING.md` or make it visible using GitHub's new issue template feature.

Ref: #334

### PR DESCRIPTION
**Pull request by thehamstermuffin**
This PR adds information to generate stacktrace.

Closes #369

### CODE REVIEW

**Comment by tobbi** [comment]
I'm not sure if the Mozilla Docs page is the right place to go, a lot of information on that site is Firefox-specific.

**Comment by thehamstermuffin** [comment]
> I'm not sure if the Mozilla Docs page is the right place to go, a lot of information on that site is Firefox-specific.

@tobbi is [this](http://www.rioki.org/2017/01/09/windows_stacktrace.html) a better source? Sorry I have no experience generating stack traces.

**Comment by tobbi** [comment]
> > I'm not sure if the Mozilla Docs page is the right place to go, a lot of information on that site is Firefox-specific.
> 
> @tobbi is [this](http://www.rioki.org/2017/01/09/windows_stacktrace.html) a better source? Sorry I have no experience generating stack traces.

This appears to be a programmer-oriented link. I think we need to write some instructions ourselves. For Linux, gdb should be used, for Mac lldb and for Windows maybe WinDbg ? I think labelling that issue as good first issue might have been a bit overkill as it requires in-depth knowledge of those OSes. Anyway, if you want to help with it, feel free.

**Comment by thehamstermuffin** [comment]
Ok, I'll check those functions and try to write the instructions.

**Comment by tobbi** [comment]
Hey, I'll assume you're not interested in this anymore. Therefore, I'm closing this.

**Pull request closed without merging**
