### PR TITLE
ST OST - More songs for the Icy Island

### PR DESCRIPTION
**Pull request by Curly68**
I finally came back with more music :)
I decided to go with a bit of a different vibe in some of the songs, since the [Music Document](https://github.com/Rusty-Box/wiki/blob/music-list/Music.md) allowed me to do that in specific cases like the underwater, cave and especially the Crystal Mine themes.

I was also requested to do a alternative versions of some songs too for more variety in the game's OST.

- midday.ogg - Surface level midday theme.
- midday_alt.ogg - Alternative version of that theme.
- cavetheme.ogg - Main cave theme, based on the original Wantsi version although it also has some original parts.
- cavetheme_alt.ogg - Alternative cave theme, straight up cover of the original cave theme by Wantsi
- crystalmine_intro.ogg - Meant to be used in the intro part and cutscene of the Crystal Mine level
- crystalmine_main.ogg - Main theme of the Crystal Mine level.
- underwater.ogg - Underwater level theme.

Like the previous pull request, the license of these songs is CC-BY-SA 4.0

### CODE REVIEW

**Comment by VincentAraneo** [comment]
question. Do you plan to make music for Rooted Forest?

**Comment by Curly68** [comment]
I am thinking of doing some tracks for that world, although I'm not sure if i can manage to do all of them. I invited a friend of mine who's also another experienced composer to the Supertux Discord btw, she was really interested in helping me and the project and maybe she can do the remaining world 2 and world 2.5 tracks if she wants to.

**Comment by VincentAraneo** [comment]
@Curly68 In fact, I'm a composer! But I make music in the LMMS, in the musics, I use samples from Supertux, because it's my favorite game. So I could do the music. if you pass me the samples you use for the music or the program you use.

Here my gmail so you can contact me: vincentaraneo@gmail.com

**Comment by NickerAban** [comment]
intelligent

**Comment by Curly68** [comment]
@VincentAraneo Well...... the problem is that i tend to use lots of sample packs and SFZ that can be  and/or VSTs that you cannot exactly turn them into samples without making them lose a lot of their spark. I also use Renoise, a DAW/Tracker hybrid which is different from the more traditional piano roll program LMMS is based on. So i don't really know how to help here.

**Review by Rusty-Box — APPROVED** [review]

**Comment by Curly68** [comment]
Heya, we not merge this yet? I've noticed that some songs still need some polishing. For example i noticed some awkward chord progression in a few songs and I'm on the process to fix that. I will tell all of you when It's ready to be merged again.

**Pull request merged**
