### PR TITLE
Remove vsync option

### PR DESCRIPTION
**Pull request by brmbrmcar**
It isn't consistent between systems, and can lead to unfair advantages such as in speedrunning.

### CODE REVIEW

**Comment by maxteufel** [comment]
As far as I understand this, it it designed to improve the gameplay experience.

SuperTux is a game in the first place, not solely targeted to speedrunning. Hence, we want to improve gameplay for everyone. Thus I don't see a need to remove this.

**Comment by brmbrmcar** [comment]
Vsync doesn't improve it though, especially when it doesn't work on half of all systems. Even with it off, there doesn't seem to be any tearing to me. It isn't just hardcore speedrunners affected; if anyone wanted to try something together on different systems it could cause problems because one runs at a different rate.

**Comment by brmbrmcar** [comment]
It also varies difficulty, because it then runs at a different speed.

**Comment by maxteufel** [comment]
Closing as per https://github.com/SuperTux/supertux/pull/780#issuecomment-368002272 (and citing https://github.com/SuperTux/supertux/issues/287#issue-123479644) after discussion with the team.

**Pull request closed without merging**
