### PR TITLE
Badguy improvements

### PR DESCRIPTION
**Pull request by Alzter**
[ci skip] [skip ci] Improvements to a handful of badguys that range from cleanups to re-sprites.

This affects these badguys:
• Mr. Bomb
• Haywire (Incomplete)
• Poison Ivy / Walking Leaves
• Leafshot
• Snail (May need adjustments)
• Zeekling
• Owl

Currently incomplete. To-do: Haywire's frozen and ignited/running animation

### CODE REVIEW

**Comment by tobbi** [comment]
Since this is WIP, I won't be merging it for 0.6.0.

**Comment by weluvgoatz** [comment]
I can say that I do enjoy the new haywire sprites, I thought they would look bad but they actually seem quite cool. I also like the new owl sprite and the new snail sprites, though I do suggest readding the old snail sprite alongside the new one, like an extra sprite, because the new snail fits good with the forest but not with ghost or castle levels. Kind of like how you can select the milestone 1 jumpy as an extra sprite...

I also enjoy the new zeekling sprite. It looks good in-game, but I did feel like it felt a bit robotic and mechanical. Maybe its body should move as it flies and it should show some emotion in the face, similar to the old one?  Still a great improvement over the old one.

As for the new poison ivy and walking leaf sprites, they are mediocre, in my opinion. Maybe they should feel a bit more leaflike and fluffy, similar to the old ones? I also suggest making the shading a little more subtle, as too much shading does not look very good on the tiling of the forest. They also do not fit with the graphic styles of the game.  The shape of these ones also don't look very good going up slopes. As far as animation goes, good job! It is consistent and smooth. But just please change the shape and shading of them a small bit, maybe even add some more detail to feel a little more leaflike, and then they will be perfect.

**Comment by Alzter** [comment]
Thanks for the criticism @weluvgoats.
I was thinking for the snail I might re-colour the shell purple and perhaps re-do the body to look more like the existing sprite (green skin and all), and possibly re-shade Poison Ivy, Walking Leaves and Leafshot to look less flat.

**Comment by weluvgoatz** [comment]
@Alzter : Sounds good!

**Comment by Alzter** [comment]
In retrospect these new graphics aren't really *that* much better then the existing ones.

**Pull request closed without merging**
