### PR TITLE
Add a few more add-on types

### PR DESCRIPTION
**Pull request by weluvgoatz**
This should add 2 things: 
1) The addon can now be type "Textures" 
2) If the addon is an invalid addon type, it should default to "Add-On"

### CODE REVIEW

**Comment by weluvgoatz** [comment]
Is this going to be considered?

**Comment by serano01** [comment]
Do we have even any Add-Ons which are simply textures? Or is it meant for Add-Ons like the Desert World?

**Comment by weluvgoatz** [comment]
A proposed idea was to have SuperTux Texture Packs, which are addons that
change the look of the game, similar to Resource Packs in Minecraft. While
there are currently no Texture Packs in SuperTux, artists might be inspired
to make some when type "Textures" is added, such as 8-bit textures,
greyscale textures, realistic textures, etc....

**Comment by weluvgoatz** [comment]
@serano01 said this won't be considered, so I close it.

**Pull request closed without merging**
