### PR TITLE
Update GLM to latest version v1.0.1

### PR DESCRIPTION
**Pull request by tobbi**

### CODE REVIEW

**Comment by MatusGuy** [comment]
remove glm

**Comment by tobbi** [comment]
> remove glm

Remove @MatusGuy from the SuperTux team.

**Comment by tobbi** [comment]
Hrm.
 
```
/home/runner/work/supertux/supertux/external/glm/glm/detail/func_packing.inl:20:3: error: unsafe buffer access [-Werror,-Wunsafe-buffer-usage]
```

**Comment by MatusGuy** [comment]
Why do we need to update glm?

**Comment by tobbi** [comment]
I feel like being on a release commit is better than being on some arbitrary commit.

**Comment by tobbi** [comment]
I'm gonna close this because of https://github.com/g-truc/glm/issues/1269 mainly.

**Pull request closed without merging**
