### PR TITLE
Explosion light sprite fades in and out smoothly

### LINKED ISSUE #960: Make ambient light spots fade in and out
**SuperTux version: 0.6.0 Alpha 3**
**System information:** *Windows 10*

I feel like the ambient light spots created by things like explosions, fireballs, and enemies should fade in and out instead of appearing suddenly.

### PR DESCRIPTION
**Pull request by MatusGuy**
The explosion light sprite now fades in and out in a smooth fashion.

fixes #960

### CODE REVIEW

**Comment by tobbi** [comment]
Can you upload a short video so I don't have to compile?

**Review by Rusty-Box — APPROVED** [review]

**Comment by Frostwithasideofsalt** [comment]
what's the status on this?

**Review by Frostwithasideofsalt — APPROVED** [review]
works. never twerks. congrats.

**Comment by tobbi** [comment]
Can you rebase please? This should fix the linter issues.

**Comment by MatusGuy** [comment]
> works. never twerks. congrats. 

And do you have any comments about the way the explosion looks?

**Comment by Frostwithasideofsalt** [comment]
> > works. never twerks. congrats.
> 
> And do you have any comments about the way the explosion looks?

i think it's pretty twerked up. 
_or in other works i think it looks fine_

**Pull request merged**
