### PR TITLE
Miscelaneous badguy tweaks

### PR DESCRIPTION
**Pull request by Hume2**

### CODE REVIEW

**Comment by Hume2** [comment]
@tobbi , could you do something with that connection error?

**Comment by Hume2** [comment]
It looks like it has fixed itself.

**Comment by Hume2** [comment]
@tobbi , it's broken again.

**Comment by Hume2** [comment]
I looks like the Travis CI randomly throws errors.

**Comment by Savsish** [comment]
@Hume2 There was a commit that added jump sound for Jumpy. Now it's gone. Why?

**Comment by Hume2** [comment]
@Savsish It was a terrible sound. I got that I'm not good enough to make sounds. I just needed one commit because the travis CI errored.
The other reason is that it was too noisy. The sound was hearable even very far away. The distance bias doesn't seem to work correctly.

**Comment by Savsish** [comment]
@Hume2 Could you attach the code and jumpy.ogg sound in a hope, that they don't get lost forever. Also i'm very curious to hear, how the jumpy.ogg sounds like.

**Comment by Hume2** [comment]
@Savsish I'm sorry, I don't have it anymore.

**Comment by Savsish** [comment]
@Hume2 I'm mad that you don't have it anymore. Maybe could someone make a nicer sound for Jumpy and push the commit here?

**Comment by Hume2** [comment]
Burning and melting
see https://youtu.be/7K-d0nf1nrI

**Comment by tobbi** [comment]
Melting graphics is great, burning could use some work. Basically, I believe that one big flame might look better.

**Comment by tobbi** [comment]
I am not sure how difficult that's gonna be: But would it be possible for you to show the original badguy with reduced transparency on the first frame of the melting graphics? That way it might look like it's a smooth transition.

**Comment by 165your4** [comment]
I like all these changes, but shouldn't the old spike tiles be left in for backwards compatibility?

**Comment by brmbrmcar** [comment]
Looks awesome.

**Comment by brmbrmcar** [comment]
How do you add images to a repository?

**Comment by Hume2** [comment]
git add
Or don't you mean anything else?

**Comment by brmbrmcar** [comment]
You have to do it via the terminal?

**Comment by Hume2** [comment]
I do everything via the terminal because all the guis seem me to be quite dull.

**Comment by brmbrmcar** [comment]
OK. I sometimes have bugs. Thank you.

**Comment by mahboi** [comment]
I just saw this today, and I must say, I **really** dislike this. In my opinion, it's too graphic and it doesn't fit the style of the game as I see it.

**Comment by MarkkusCraft123** [comment]
I agree with @mahboi , these new animations really don't fit the overall style of the game. Sure, it might work for the Halloween levels, but that's one thing.

**Comment by tobbi** [comment]
@Hume2 Can you address the comments in a new pull request?

**Comment by mahboi** [comment]
By "new", do you mean #164?

**Pull request merged**
