### PR TITLE
Improve the secret in Ice in the Hole

### PR DESCRIPTION
**Pull request by brmbrmcar**
The community didn't like the old one, and also the door is not going to go well for new players who have never seen it before.

### CODE REVIEW

**Comment by brmbrmcar** [comment]
Before modification: https://www.youtube.com/watch?v=E0x66dollCY

After modification: https://www.youtube.com/watch?v=5g4TFNWmjsY

**Comment by tobbi** [comment]
@maxteufel I assigned you to this, not sure whether you're the right person to handle that.

@Rusty-Box or @serano01 might want to give input as well.

**Comment by serano01** [comment]
Quite hard to find now, but at least it doesn't require the door anymore.

**Comment by Rusty-Box** [comment]
I don't really get the issue with the original one. Sure it makes you skip a bit at the start but it's not so tragic.

**Comment by tobbi** [comment]
Perhaps add a few more visual cues?

**Comment by brmbrmcar** [comment]
The main problem is that you have never seen a door before at this point, and it is not fair to put it in as part of a secret.

**Comment by tobbi** [comment]
I actually meant a less obvious clue. 🇾🇪

**Comment by maxteufel** [comment]
I'm undecided about this. I'd leave it open to @SuperTux/level-designers.

I agree with @serano01 that it looks extremely hard to find (without the clue, I have only watched the two original videos - and apparently @tobbi thinks the clue is too obvious).

I also agree with @Rusty-Box. I don't see a problem with the current secret. Possibly it's actually intended to have you skip a bit of the level.

I don't mind if it's the first time you see a door. That's a general problem anyway.

Hence I'd be rather inclined to close this pull request - but I'll let @SuperTux/level-designers decide about it.

**Comment by Rusty-Box** [comment]
btw. with "original" I didn't meant the door version. I was talking about the walk way that was there since milestone 1.

**Comment by brmbrmcar** [comment]
The walkway wasn't too bad, except it meant you could skip nearly all the rest of the level.

**Comment by maxteufel** [comment]
Oh I pretty much don't care. If you believe re-adding that walkway from M1 (yes, I vaguely remember) is the right thing, @Rusty-Box, feel free to do so (by submitting a pull request). I just want some decision (merge/change something else/close) on this PR.

**Comment by Rusty-Box** [comment]
@brmbrmcar Actually it wasn't that much you could skip. It was only the first couple of bad guys at the beginning. Saying that you could skip nearly all the rest of the level is a bit over exaggerated.

**Comment by brmbrmcar** [comment]
No, @Rusty-Box  just look at any 0.4.0 speedrun

**Comment by brmbrmcar** [comment]
http://mcmic.haxx.es/speedrun/supertux_2007.webm 12 minutes in

**Comment by Rusty-Box** [comment]
@brmbrmcar ok I must agree I mist the next walk way. This one is stupid. So if we remove this one it's not so bad

**Comment by HybridDog** [comment]
You could keep the door shortcut but make it more difficult to reach it. 
A wall jump is probably difficult for new players: https://forum.freegamedev.net/download/file.php?id=11607&sid=f74bc1225c732995197a60d0e47062cb

**Comment by weluvgoatz** [comment]
Can this be closed? It was removed anyway.

**Comment by serano01** [comment]
Has been changed in 0.6.0, so I'm closing this.

**Pull request closed without merging**
