### PR TITLE
Handle string collisions in tinygettext properly

### PR DESCRIPTION
**Pull request by tobbi**
Depends on SuperTux/tinygettext#4

### CODE REVIEW

**Comment by tobbi** [comment]
This should fix #309

**Comment by maxteufel** [comment]
Does this also fix #360?

**Comment by tobbi** [comment]
It only remedies it at most. inter-langpack-collisions are still an issue since they're both marked as override.

**Comment by Hume2** [comment]
r+

**Comment by maxteufel** [comment]
Looks good to merge, but depends on SuperTux/tinygettext#4 being actually merged too.

**Comment by tobbi** [comment]
This got superseded by #504, leper's solution is easier with a lot less changes and bug-free.

**Pull request closed without merging**
