### PR TITLE
Automatically update translation templates

### PR DESCRIPTION
**Pull request by tobbi**
(I'm hereby testing the automatic translation template updater, using my own translations repo for now).

### CODE REVIEW

**Comment by tobbi** [comment]
Well, this doesn't work. If anyone who knows travis well enough knows what's wrong, feel free to tell me.

**Comment by christ2go** [comment]
You must add transifex-client, pip3, easy_install3 and all the other packages the added scripts are using as a dependency.

**Comment by maxteufel** [comment]
This is the most terrible way of doing this. If anything, the translation templates should be (re)generated locally when changing some source code. If we put the translations/ repo content back into our main repo (I was waiting on @maths22's repo reorganization plans for this), then we can easily add this into CMake to automagically handle this when compiling to test the changes.

**Comment by christ2go** [comment]
@maxteufel I only took a look at the travis run (https://travis-ci.org/SuperTux/supertux/jobs/339744411). It complains about those things, but you're right, doing this locally is better.

**Comment by maxteufel** [comment]
Oh ­­- I was just looking at this pull request. That's a different branch.

**Comment by tobbi** [comment]
This was a test. And you're right. It is horrible, that's why I closed it. I will work on the transifex client thingy and check that out.

**Pull request closed without merging**
