### PR TITLE
(WIP) Tux revamp

### PR DESCRIPTION
**Pull request by Alzter**
I'm revamping the Tux sprites to be more consistent, lively and appealing.

### CODE REVIEW

**Comment by weluvgoatz** [comment]
And I'm helping with this issue ;)

**Comment by windowsdylan** [comment]
Firehat Buttjump animation fix
[tux.zip](https://github.com/SuperTux/supertux/files/3366387/tux.zip)

**Comment by Alzter** [comment]
> Firehat Buttjump animation fix
> [tux.zip](https://github.com/SuperTux/supertux/files/3366387/tux.zip)

This is not needed as the latest update will handle the fire and ice hats as separate layers instead of being merged with Tux's sprite.

**Comment by serano01** [comment]
Will this include the new climbing animations, by the way? This is something I've been waiting for a long time, because the old animation is so horrible.

**Comment by Alzter** [comment]
> Will this include the new climbing animations, by the way? This is something I've been waiting for a long time, because the old animation is so horrible.

Yes.

**Comment by Alzter** [comment]
There's a new jump animation for Big Tux!

**Comment by serano01** [comment]
What's missing for this PR to be ready? I want to see this stuff ingame.

**Comment by serano01** [comment]
By the way, I've tested it. Small Tux stucks in the ground at the start of the jump, and Power-Ups like the fire hat are invisible. Apart from that, great work.

**Comment by Rusty-Box** [comment]
@Alzter Is there still stuff left to do in here?

**Comment by Alzter** [comment]
> @Alzter Is there still stuff left to do in here?

Yes. Quite a lot actually.

- Skidding (make it more animated and transition into walking)

- Ducking (make it a proper animation instead of one frame)

- Backflip (make it more fluid, improve perspective, draw inspiration from Grumbel's concept)

- Buttjump (Doesn't transition nicely from the new jump, could use more liveliness like Tux doing a flip before going down like the ground pound in Yoshi's island)

- Buttjump landing (Make the buttjump actually land instead of the stupid bounce, inspire off Grumbel's concept for it)

- Worldmap ladder (Is this even used, can we remove it)

- Worldmap boat (Ugly)

**Comment by weluvgoatz** [comment]
@Alzter Don't forget about the death animation and the kicking animation.  Also, I have a locally fixed offset for small tux's jump, but it requires this PR to be merged first.  I also have a local implentation of a falling anim, but it also requires this PR to be merged.  Be aware you can always make multiple pull requests.

**Comment by serano01** [comment]
> @Alzter Don't forget about the death animation and the kicking animation. Also, I have a locally fixed offset for small tux's jump, but it requires this PR to be merged first. I also have a local implentation of a falling anim, but it also requires this PR to be merged. Be aware you can always make multiple pull requests.

We should consider this, if the new release for December is still a thing.

**Comment by Zwatotem** [comment]
@weluvgoatz isn't it possible to commit to some else's pull request, if he allows for it?

**Comment by weluvgoatz** [comment]
@Zwatotem I am not sure.

**Comment by Alzter** [comment]
> @weluvgoatz isn't it possible to commit to someone else's pull request, if he allows for it?

IT IS NOT FINISHED YET. I would much rather all of the new sprites are finished and added to the game in a complete and polished state, rather than being incomplete and buggy like a lot of other things that have been added in the past. I haven't exactly been working on these as of recently but by all means if anyone wants to help make the Tux animations that aren't done yet, be my guest.

**Comment by busybody42** [comment]
NO PLEASE NO!
You did your best, altzer, but it looks even WORSE than your opinion on the forest world, and your burnout and rant, ever could be. COMBINED. It's too detailed... If it has too much detail, it's an eyesore... To LITTLE, which is what you hate, and it's not very appealing or interesting...
Your tux sprites overlap with too MUCH detail... 
Denied...

**Comment by Rusty-Box** [comment]
Closing this as it seems this won't be continued any time soon.

**Pull request closed without merging**
