### PR TITLE
Fixed a bug where you could travel through magic blocks while holding…

### PR DESCRIPTION
**Pull request by Semphriss**
… a lantern of the same color by going fast enough.

I simply removed the delay before the block becomes solid.

When swimming, Tux can gain enough velocity to pass through magic blocks while carrying a lantern of a color that should make them turn solid. Levels that relies on the player's inability to pass a magic wall block while holding a lantern of a certain color can be easily broken by this.

### CODE REVIEW

**Comment by tobbi** [comment]
I think this can be merged. Build failures are unrelated.

**Comment by Zwatotem** [comment]
@tobbi Please, let me test this. I'm afraid that cooldown was there for a reason.

**Comment by Semphriss** [comment]
I thought the same, but I don't seem to encounter any error in normal levels. If there were bugs, they might have been unknowingly fixed since the might-be-bugfix has been added.

I can try to investigate when and why this has been added, and if there are any known bugs related to that.

**Comment by Semphriss** [comment]
Related issue : https://github.com/SuperTux/supertux/issues/335 : It was mentionned that it was to prevent flickering, but there is a minimum lighting time (of 1 second) which already fixes the problem.

Still looking at the commit log for other relevant information.

**Comment by Semphriss** [comment]
I found 2 relevant commits :
- 4dec9ee4e :
> Author: LMH <email removed>
> Date:   Thu Jul 17 20:35:09 2014 -1000
>
>    Reduced the value of SWITCH_DELAY for magic blocks to prevent lanterns (and Tux) from prematurely passing through them while in free-fall
- 5f6321f7860167eb2d4ce6ae3f909eda555725b3
> Author: Christoph Sommer <email removed>
> Date:   Sat Aug 12 16:27:19 2006 +0000
> 
>    Reduced switching delay from 1s to 0.1s

The "feature" was added between 7ddb11ba21077cc2d7dfc2e95cbf1b3736ddbb68 and 5f6321f7860167eb2d4ce6ae3f909eda555725b3. There are no commits between them that affects magicblock.cpp. According to Git, "Reduced switching delay from 1s to 0.1s" actually *added* said delay. (That was back in 2006).

The commit adding the delay-before-switching (which was back then of one full second) doesn't seem to exist, for some reason.

**Comment by Zwatotem** [comment]
I think it was there to prevent flickering in case magic block is on the edge of light source. But this value was lowered several times without complains. Merging.

**Pull request merged**
