### PR TITLE
Changed handling of Tux movement

### PR DESCRIPTION
**Pull request by Semphriss**
- Removed speed ceiling that gets applied whenever the player presses a certain direction. Now, limits are applies regardless of what the player presses, and the speed is brought back within limits smoothly rather than instantly.
- Added a boost mechanism, to help Tux gain extra velocity above speed limits for a short amount of time (useful for bumpers).
- Fixed the one-wall walljump-climbing bug.

### CODE REVIEW

**Comment by Semphriss** [comment]
@Zwatotem Any comments? I can't get very far with just an emoji :^)

**Comment by Zwatotem** [comment]
I just liked the climbing bug. But that's okay if you fixed it. Can't give feedback on the rest right now.

**Comment by Semphriss** [comment]
I removed the climbing bug because it opened the door to poor level design, both by level designers that will expect players to use it and those who don't.

We also discussed about Tux's moveset the other day, and we agreed that double-wall walljumping would be the ceiling in terms of mobility for Tux. (Ngl, I would prefer not have a fat penguin have the moveset of a ninja :eyes:)

**Comment by weluvgoatz** [comment]
This feature is good, I approve of the merge but I'll wait for others to chime in. :)

**Comment by weluvgoatz** [comment]
I remember this PR working quite well, are there any objections to it?

**Comment by Semphriss** [comment]
Merge conflicts are solved, so whenever you want :^)

**Comment by weluvgoatz** [comment]
Gonna merge this now, thanks.

**Pull request merged**
