### PR TITLE
Upgrade packages

### PR DESCRIPTION
**Pull request by tobbi**

### CODE REVIEW

**Comment by Grumbel** [comment]
Try zlib1g-dev -> zlib1g-dev:i386

**Comment by tobbi** [comment]
that did not help

**Comment by Grumbel** [comment]
`sudo apt-get upgrade` after the `apt-get update`

**Comment by tobbi** [comment]
I tried that in https://github.com/SuperTux/supertux/pull/1913/commits/d53a59f1e844786a15671cd499ec9535141aa488 https://github.com/SuperTux/supertux/runs/4373866504?check_suite_focus=true

**Pull request merged**
