### PR TITLE
Improved ghosttree sprite

### PR DESCRIPTION
**Pull request by Hume2**
Travis[ci skip]

### CODE REVIEW

**Comment by maxteufel** [comment]
@DevynCJohnson, do you have any idea on further improving this?

**Comment by maxteufel** [comment]
From IRC

```
2015-10-17 21:02:05     Tobbi  Hume2: Also, please recreate the tree sprite instead of applying fancy filters to it...
2015-10-17 21:02:14     Tobbi  How do you imagine a ghost tree?
```

```
2015-10-17 21:08:56     Tobbi  Hume2: I believe we need someone with graphics skills to draw us a new tree boss...
2015-10-17 21:09:10     Tobbi  Filters really don't help IMO
2015-10-17 21:09:42     Tobbi  Hume2: Or do you have a graphics tablet and drawing skills? ;)
2015-10-17 21:10:11     Hume2   Tobbi: No, I don't. I draw only by mouse.
2015-10-17 21:10:16     Tobbi  hmm, ok
2015-10-17 21:10:19     Tobbi  same here
2015-10-17 21:10:25     Tobbi  My drawing skills are not really good for anything.
```

**Comment by DevynCJohnson** [comment]
I will see what I can do with the https://github.com/SuperTux/supertux/tree/master/data/images/creatures/ghosttree/ghosttree*.png files

**Comment by Karkus476** [comment]
@DevynCJohnson Any updates?

**Comment by DevynCJohnson** [comment]
@Karkus476 , I have not heard anything from anyone in the SuperTux chat-room about my proposed GhostTree design.

**Comment by tobbi** [comment]
Just post the proposed design here or on the forums, please.

**Comment by Karkus476** [comment]
@DevynCJohnson Although we would be willing to do as you say, it would not make sense to do this. At worst, you could at least use supertux-devel@lists.lethargik.org to contact us, where we can all see it. Even better, just drag your images into the comment box here or in an issue, and we will sort them out for you. We'd be grateful for anything you could create as we are low on numbers especially where design is concerned.

**Comment by DevynCJohnson** [comment]
@Karkus476 , true, I understand what you mean. However, I still have not heard anything yet about what the team thought of my proposed ghost-tree design.

**Comment by tobbi** [comment]
Hey. Where is your design proposal, again?

**Comment by DevynCJohnson** [comment]
@tobbi , I had proposed it in the SuperTux chat-room. If you would like, I can email someone the GIMP-XCF files and the team can have/own my design under any license the team wants. I cannot put a lot of time into the SuperTux project. I do not intend on being a long-term contributor. I just wanted to contribute a little temporarily. Sometimes, I like to contribute a little to various open-source projects by committing some code or files. However, after spending time with the SuperTux team, I see that my contributions can only be effective and beneficial if I spend time in the mailing-list and chat-room. However, I do not want to spend that much time for a few minor contributions. Plus, I do not use SuperTux (although an author for my website publishes many tutorials and documentation about the SuperTux Level Editor), so this is not a project I am "super" passionate about like I am with the EnlighterJS and Geany software projects. I hope you all understand. I have no problem with the SuperTux team; I just cannot be a beneficial contributor if I am not willing to spend a lot of time and effort into learning the projects needs and "culture". I contributed temporarily to other software projects (like "Clementine" when I added additional equalizers). For such projects, I could easily and effectively help the project by submitting a few small contributions. However, I do not think I can effectively help SuperTux without using more time and effort.

**Comment by Mathnerd314** [comment]
@DevynCJohnson From IRC I believe the comment was that it was "too scary" and not really an improvement.

Similarly Hume's is not much of an improvement either since it is just "fancy filters".

Here are some ghost tree images I found online for reference, from least to most scary:


A SuperTux-style ghost tree should fit in with the forest art style:

A sketch from grumbel:

His guide on how to draw things: http://pingus.seul.org/~grumbel/gimp/drawing/

**Comment by brmbrmcar** [comment]
Hume2's is an improvement.

**Comment by DevynCJohnson** [comment]
@Mathnerd314 , yes, I know. That is exactly what I mean. To provide beneficial contributions, I need to put more time into the team. However, I just wanted to temporarily provide a few contributions, but I see that that is not feasible without putting a lot of time into being a team member. I understand and I accept that. I am sorry that I could not provide helpful contributions to the team.

**Comment by brmbrmcar** [comment]
It only needed a bit of improvement in my opinion. I cannot do graphics. It is not too scary at all.

**Comment by tobbi** [comment]
@DevynCJohnson Don't worry about not being able to contribute more. I guess someone else will pick it up and finish it.

**Comment by brmbrmcar** [comment]
Yes.

**Comment by DevynCJohnson** [comment]
Thanks. I wish you all luck in your project. By the way, you may want to add this link to your wiki for the Level Editor - http://dcjtech.info/topic/gaming/#supertux

*WARNING:* My website has ads. However. the ads will not infect your system (yes, some people think the ads on my website can infect their system).

**Comment by tobbi** [comment]
Indeed, I wanted to get that done a month ago, at least.

**Comment by tobbi** [comment]
http://supertuxproject.org/contact.html A link to the guides is at the bottom (in case I haven't answered this question before).

**Comment by Hume2** [comment]
Closing since noone is really working on it.

**Pull request closed without merging**
