### PR TITLE
Avoid drawing unnecessary things when we're about to quit

### PR DESCRIPTION
**Pull request by tobbi**
Also, don't update integrations for every tick, that's way too often and wastes CPU cycles.

### CODE REVIEW

**Comment by Vankata453** [comment]
Is there a case when `ScreenManager` isn't running, other than when the game is being quit?

**Comment by tobbi** [comment]
> Is there a case when `ScreenManager` isn't running, other than when the game is being quit?

Not that I know of.

**Comment by Vankata453** [comment]
Additionally, while the game quit screen fade is being performed, wouldn't not further drawing the UI elements make them disappear immediately before the fade starts, causing for a visual inconsistency? I will test this soon to check, this is just an observation from looking at the code.

**Comment by Vankata453** [comment]
Testing shows that now quitting the game with transitions enabled makes the UI disappear before the fade out happens. Considering this didn't happen before the change, and keeping in mind `ScreenManager` is only not running (shouldn't draw UI elements, process sound or events) when quitting the game, I'm not sure whether the changes (other than the integration update ones) provide a significant benefit.

**Comment by Vankata453** [comment]
What is the optimization achieved in this PR? Is it significant enough to warrant not drawing UI elements on screen fade-out?

**Comment by tobbi** [comment]
It's drawing them now

**Comment by Vankata453** [comment]
> It's drawing them now

It's only drawing the menu on fade-out, still hides FPS counter, player position, etc... There should be some benefit from not drawing those UI items to warrant changing their behaviour, and I'm not sure what it is.

**Comment by tobbi** [comment]
Fine, you want the pr closed, I'll close the pr.

**Comment by Vankata453** [comment]
Sorry, I only wanted to ask a question regarding the PR, so I can justify a review. For example, the integration change seems beneficial. For this part I genuinely didn't know what benefit it serves, so I'm asking to hear why you decided to implement it.

**Comment by tobbi** [comment]
Reason I implemented this was because shutdown always felt slow to me

**Comment by Vankata453** [comment]
Did it feel slow when the menu was hidden?

**Pull request closed without merging**
