### PR TITLE
ST OST - Two forest songs 

### PR DESCRIPTION
**Pull request by Curly68**
Here are two new forest songs for Supertux 0.7 that I've made lately.

- forest_new.ogg - A new version of the old forest theme.
- forest_new_alternative.ogg - An alternative version, meant for more fast paced levels.

These two songs are based on forest.ogg and forest3.ogg by Wantsi, 
However they also have some original songwritting in between.

I will continue making new songs for the forest world as soon as i can.
Sorry for my 3 month absence

### CODE REVIEW

**Review by Rusty-Box — COMMENTED** [review]
For consistency, I'd recommend naming these two files midday and midday_alt. Other than that everything looks good 👍

**Comment by Curly68** [comment]
The problem is that there are already two existing "midday" and "midday_alt" songs located in the antartic music folder, which could lead to some confussion in for example the AUTHORS file
Maybe "forest_midday" and "forest_midday_alt" would be better?

**Comment by Rusty-Box** [comment]
> The problem is that there are already two existing "midday" and "midday_alt" songs located in the antartic music folder, which could lead to some confussion in for example the AUTHORS file Maybe "forest_midday" and "forest_midday_alt" would be better?

Good catch ☝️  Yeah, let's call them forest_midday and forest_midday_alt instead.

**Comment by Curly68** [comment]
Ok, i think that it should be all good by now.

**Review by Rusty-Box — APPROVED** [review]

**Review by weluvgoatz — APPROVED** [review]

**Review by mrkubax10 — APPROVED** [review]
This is very good.

**Pull request merged**
