### PR TITLE
Add `srand()` to scripting API.

### PR DESCRIPTION
**Pull request by tylerandari13**
`srand()` allows you set the seed that `rand()` will use.

Also its not called something like `set_seed()` because its called srand in Squirrel. (see http://squirrel-lang.org/squirreldoc/stdlib/stdmathlib.html#srand)

### CODE REVIEW

**Comment by tobbi** [comment]
I guess it makes sense. Just wondering why we don't use the Squirrel implementation of that in the first place.

**Comment by Vankata453** [comment]
We don't use the Squirrel implementation probably, because randomizing from scripts is intended to be a part of the game's randomization flow? So when you replay a level which uses `rand()` with the same seed as before, you get the same randomizations.

**Comment by Vankata453** [comment]
Also, on the topic of this PR, I'm not really sure what the purpose for this function would be, because it would essentially make randomizations be the same, if set with the same seed. Of course, the seed could be set from time (did Squirrel provide a function for that?), though the game does that on startup anyways, so I don't know why you'd want to do that.

An additional thing to point out is that this function would set the randomization seed globally for the game, which means it will affect other levels as well. However, that wouldn't be a problem, I believe.

**Comment by tylerandari13** [comment]
Closing this. Discussed this on the Discord and tbh theres not much to gain from an srand function, and theres another issue regarding the rand function bringing the same random numbers every time you start the game, so i might (emphasis on *might*) look into that in another PR.

**Pull request closed without merging**
