### PR TITLE
Jump to path node immediately

### PR DESCRIPTION
**Pull request by tobbi**
This currently only works for the platform thing. I didn't add the same thing into the Tilemap class yet.

I don't know if this has further repercussions.

### CODE REVIEW

**Comment by tobbi** [comment]
@Rusty-Box Try this out, please.

**Review by Rusty-Box — CHANGES_REQUESTED** [review]
The `set_node(x);` script works on its own pretty well. However, after using the `set_node(x);` script and then running the `start_moving(bool);` script, the object/tilemap will not start moving anymore.

**Review by Rusty-Box — APPROVED** [review]
Now the `start_moving();` script works fine after the `set_node(x);` was run. Neat!

**Review by MatusGuy — APPROVED** [review]

**Review by tobbi — COMMENTED** [review]
If I could approve, I would. 

Here's my "Approve" review:

A very exceptional pull request, Tobbi. Only a person as intelligent and superb as you could produce such superior code. Spread the word.

**Pull request merged**
