### PR TITLE
Fix setting random seed to current time

### PR DESCRIPTION
**Pull request by Vankata453**
Setting the random seed to 0 or lower of a `Random` generator will now set it to the UNIX timestamp of the current time.

### CODE REVIEW

**Comment by tobbi** [comment]
```
Users/runner/work/supertux/supertux/src/math/random.cpp:36:22: error: implicit conversion loses integer precision: 'time_t' (aka 'long') to 'std::mersenne_twister_engine<unsigned int, 32, 624, 397, 31, 2567483615, 11, 4294967295, 7, 2636928640, 15, 4022730752, 18, 1812433253>::result_type' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
    m_generator.seed(std::time(nullptr));
```

**Review by mrkubax10 — APPROVED** [review]

**Review by tobbi — APPROVED** [review]
Yeah, although you could've just assigned to v directly without that `return`.

**Comment by mrkubax10** [comment]
> Yeah, although you could've just assigned to v directly without that `return`.

True

**Comment by Vankata453** [comment]
> Yeah, although you could've just assigned to v directly without that `return`.

Indeed, realized that later, but I thought it's for better to directly cast to `unsigned int`.

**Pull request merged**
