### PR TITLE
Added scripting to rotating spotlight object + some changes

### LINKED ISSUE #768: Spotlight: expose to scripting API
Expose spotlights to the scripting API. That means:

- adding a name property
- starting, stopping the rotation using the scripting API
- enable or disable light emission from scripting API
- change speed and direction using scripting API
- change color using scripting API

### PR DESCRIPTION
**Pull request by Semphriss**
Fixes #768 

Added setters, faders, and easers for angle, rotation speed, and light color.

Also changed the direction variable to consider not rotating at all.

Also changed GameObjects to handle FadeHelpers globally. This will require a refactor of all GameObject-inheriting classes to call GameObject::update(float) where necessary.

Consideration: Although the "direction" property seems needless (as clockwise/counter-clockwise rotation can be achieved using positive or negative values), I chose to leave it there so that scripters can easily change the direction of a spotlight - or stop it completely - without having to know/remember its original speed in some way if they want to reset it at a later point.

### CODE REVIEW

**Comment by Semphriss** [comment]
Fixes #768

**Comment by weluvgoatz** [comment]
This works great! I do have a small suggestion though; the "time" and "angle" parameters seem to be reversed in the scripting functions sometimes (see lines 59-62 of the src/scripting/spotlight.cpp, but this issue shows up throughout the file).

I don't know if this is intentional, as normal players won't see the difference if it's documented one way or another, but if it ends up being an oversight it should be fixed.  Either way, I will merge it once that is fixed or turns out to be intentional.  Thanks for this PR!

**Comment by Semphriss** [comment]
image

If you are refering to this, it's normal; it's because the fade helper expects time to be first, but in scripting, I wanted to make it consistent (value is always the first argument, time is the second, and easing the third) to make it easier for scripters.

I double-checked, and arguments are ordered properly everywhere :D

**Comment by weluvgoatz** [comment]
Thanks for clarification, and since it all works as intended, I'll merge this.

**Pull request merged**
