### PR TITLE
Tux and Penny Design Revamp

### PR DESCRIPTION
**Pull request by Rusty-Box**
After many years of SuperTux it is time to give our main character a desperatly needed glow up!

**This PR contains:**
- Fully re-drawn and re-animated sprites for both Small and Big Tux
- Many new animation for newly added mechanics (i.e. sliding, crawling etc.)
- A couple properly animated sprites for Penny

**List of coding changes required:**

- [x] Big + Small Tux - must call for the new **boost** action for swim boosting underwater
- [x] Big + Small Tux - must call for the new **slide** action for sliding
- [x] Big + Small Tux - must call for the new **slidejump** action for jumping while sliding
- [x] Big + Small Tux - call new **scratch** action before **idle** action and after **stand** action
_(Note: idle action should play endless until Tux moves again instead of reverting back to stand action mid-way!)_
- [x] Big + Small Tux - **climbing**, **floating**, **swimming** have been renamed to **climb**, **float**, **swim** in the `.sprite` file
---
- [x] Small Tux - remove sprite rotation for slidejump
- [x] Small Tux - must call for the new **slidegrow** action for getting an Egg powerup while sliding
- [x] Small Tux - must call for the new **climbgrow** action for getting an Egg powerup while climbing
_(Note: Tux should also not let go of climb-ables while getting a powerup!)_
---
- [x] Big Tux - must call for the new **stomp** action after touching the ground during a buttjump
- [x] Big Tux - remove sprite rotation for backflip
- [x] Big Tux - remove sprite rotation for slidejump
- [x] Big Tux - must call for the new **crawl** action for crawling

**_Note: Everything listed under `Big Tux` and `Big + Small Tux` also applies to Fire Tux, Ice Tux, Earth Tux and Air Tux!_**

Known bugs that need fixing:

1. [x] Small Tux's walk animation doesn't seem to load properly when in motion. It seems to work however when standing still first and during the main menu.

https://user-images.githubusercontent.com/20615048/202192920-a6ff5f17-2fef-4c19-aa6a-8fab53e8cab2.mp4

2. [x] Some animations (e.g. Big Tux idle animation) occasionally don't load immediately causing the previous animation to freeze temporarily instead of transitioning to the next animation immediately.

https://user-images.githubusercontent.com/20615048/202193431-1e8b9396-9d87-4b0a-9916-f9e480e1363f.mp4

---

The **Santa Tux** entry in `tux.sprite` will most likely be deleted later, as all versions of Tux should wear a Santa hat during Christmas season going forward - Sprite updates pending!

### CODE REVIEW

**Comment by FILIPOKonGithup** [comment]
hey Rusty-Box i have a question. when will the revamped nolok desgin will be done?

**Comment by Rusty-Box** [comment]
> hey Rusty-Box i have a question. when will the revamped nolok desgin will be done?

I can't give any concrete date as I haven't focused much on it just yet.
Sprite concepts were made and I intend to work on them more around next year. There are still some more impoarnt graphics to update + make before I go work on Nolok.

**Comment by Anyone-Anonymous** [comment]
i don't know if i should be writing this here but i suggest renaming the action name "scratch" to "idle2", because when users start making supertux mods, they could make the mod character perform other actions instead of "scratching the belly". just a suggestion

**Comment by RustoMCSpit** [comment]
@Rusty-Box hi could you check out this discussion https://github.com/SuperTux/supertux/discussions/2725

**Pull request merged**
