### PR TITLE
Fixed Bug #127 Concerning the Level Introductions.

### PR DESCRIPTION
**Pull request by Karkus476**
The correct Tux animation should now show on the level intro screen.

### CODE REVIEW

**Comment by tobbi** [comment]
Not sure if you can do anything about this, but: Tux walks during the jump animation as well (which shouldn't be the case). Try changing this to the jump animation.

**Comment by Karkus476** [comment]
Done

**Comment by tobbi** [comment]
Please check the travis build errors (they're actually warnings with -Weff). Also, I'd rather not make Tux jump in the level intro when pressing space. I'd rather start the level when pressing space.

**Comment by Karkus476** [comment]
Yeah that's probably better

**Comment by tobbi** [comment]
Oh, right, you created another pull request. Closing this.

**Comment by Karkus476** [comment]
Yeah I should've said. I was stupid enough to create this pull request from my master branch :P

**Pull request closed without merging**
