### PR TITLE
Remove crack.png

### PR DESCRIPTION
**Pull request by HybridDog**
This seems to be an unused file with image data of the unstable tile object.

### CODE REVIEW

**Comment by busybody42** [comment]
That's used in many ADDONS!
And in some other levels, I think

**Comment by Rusty-Box** [comment]
@busybody42 do you have examples? I can’t think of a way it would have been used in an addon.

The unstable tile uses the same sprites located in unstable tile folder. So removing them won’t affect the unstable tile.

**Comment by busybody42** [comment]
They're used in the hard mode version of 1 - a day of doom in matties world

**Comment by tobbi** [comment]
@HybridDog A slightly off-topic question (but I couldn't get ahold of you using other means):
We're releasing 0.6.2 on May 14, 2020. We deem your contributions worthwhile for you to be included in the credits. If you want to be included, please tell us how you'd like to be listed (using your username, using your full name) before that date. If you don't respond before then, I'll assume you don't want to be listed (since you did not specify an e-mail address with your github commits, I'm assuming you'd rather stay anonymous anyway).

**Comment by tobbi** [comment]
@busybody42 Is it really *this* file that gets used? Can you try removing the file and see whether it breaks that level? As was said, we have an identical file somewhere else in the codebase.

**Comment by HybridDog** [comment]
> We deem your contributions worthwhile for you to be included in the credits. If you want to be included, please tell us how you'd like to be listed (using your username, using your full name) before that date.

You can add my username to the credits if you want to. 
I'm planning to contribute irregularly, i.e. implement something occasionally when I have time and interest.

**Comment by tobbi** [comment]
> > We deem your contributions worthwhile for you to be included in the credits. If you want to be included, please tell us how you'd like to be listed (using your username, using your full name) before that date.
> 
> You can add my username to the credits if you want to.

Done in that latest commit.

> I'm planning to contribute irregularly, i.e. implement something occasionally when I have time and interest.

I encourage that! Balance is incredibly important! I do it the same way.

**Pull request merged**
