### PR TITLE
Extra content...

### PR DESCRIPTION
**Pull request by busybody42**
This adds in an ice cannon sprite from grumbel's sketches... 
...a sprite for the ice tile from said sketch: [db945389c00b39ef6012614735aaa154-supertux-news](https://user-images.githubusercontent.com/37600842/75297492-0c6cfb80-57fe-11ea-95f8-283d497f6dc7.png)
... an extra font for this pull: https://github.com/SuperTux/supertux/pull/765
and the old mr bomb sprites, complete with the old frozen sprite...

### CODE REVIEW

**Comment by busybody42** [comment]
my frozen sprite is still in the graphics, because why not...

**Comment by busybody42** [comment]
ok, sorry... I forgot about those sprites...

**Comment by busybody42** [comment]
done...
I just forgot...

**Comment by weluvgoatz** [comment]
Does anyone know if this makes the 1/8 character work properly? If it doesn't work, then this should not be merged.  I agree that you should not put a bunch of unrelated stuff into the same PR because then we can't merge it if one thing is unwanted.

**Comment by busybody42** [comment]
...I really don't know how to add in a new font... I added the sprite for it, though... so now it's at least easier to make it actually show up in game...

**Comment by HybridDog** [comment]
> Does anyone know if this makes the 1/8 character work properly?

I think it does not work with ttf fonts (the default mode now).

**Comment by NickersonRomero** [comment]
oh

**Comment by busybody42** [comment]
I did the changes requested.

**Comment by HybridDog** [comment]
There are 122 changed files in this Pull Request, and most are probably not related to your suggested changes.

Please try to separate your changes into multiple smaller Pull Requests. 
Small Pull Requests are easier to review, and if some change is unwanted or unfinished, the other separated changes would not be blocked from merging.

> This adds in an ice cannon sprite from grumbel's sketches...
...a sprite for the ice tile from said sketch: db945389c00b39ef6012614735aaa154-supertux-news
[…]
and the old mr bomb sprites, complete with the old frozen sprite...

Are the added sprites used by the game?
If not, the [media repository](https://github.com/SuperTux/media) may be a better place for saving them.

**Comment by busybody42** [comment]
The sprites can't be used if they don't exist yet! 
Also, I was using them for a worldmap I was making...
many of the 122 changed files are just from merging pulls added to the main repository
I think...

**Comment by HybridDog** [comment]
> The sprites can't be used if they don't exist yet!
Also, I was using them for a worldmap I was making...

Sorry, my question was phrased unclearly. I don't know much about SuperTux sprites and was wondering if the proposed sprites have many possible use cases in the game or if it is better to add the new sprites to an add-on when using them.

> many of the 122 changed files are just from merging pulls added to the main repository
I think...

They are from the strange [Revert "s" commit.](https://github.com/busybody42/supertux/commit/2b9bacb1aea787ecdb57da1039189be239d93e97).
Without this commit, the changes look fine for me. 
Here's a rebased version: https://github.com/SuperTux/supertux/compare/master...HybridDog:busybody42_master_rebased?expand=1&short_path=9e306b6#diff-9e306b659526836a8b1188052406efb4

**Comment by busybody42** [comment]
well, the ice cannon and ice tiles can be used for Antarctica,
And the "s" commit was because it wasn't letting me merge, due to NEWS.md being altered
sorry

**Comment by busybody42** [comment]
Your rebased version can be used, but it's my fork you're using...

**Comment by HybridDog** [comment]
As far as I can see, the grumbel-ice.png is not registered as tile in tiles.strf, so I assume it cannot be used.

**Comment by HybridDog** [comment]
> Your rebased version can be used, but it's my fork you're using...

No, I used my fork and put your name in the branch name. I've rebased this PR because I was curious about whether the many files changed problem can be fixed easily.

Nobody has disagreed on a merge until now, so I'm applying the changes and hope that everyone is fine with them.

**Comment by busybody42** [comment]
I'm gonna try closing this because the commit was done.

**Comment by Alzter** [comment]
Someone needs to revert **[this commit](https://github.com/SuperTux/supertux/commit/023320247a4685df26eeb1dce844aab48fb94f6b)**, these "new" sprites serve little to no purpose aside from adding clutter to the game. The deprecated sprites like old Mr. Bomb were removed from this game for a reason, the ice cannon seems unneccesary and the "grumbel-ice" tile has so many things wrong with it that I couldn't help but list them all.

- The ice tile isn't even ripped properly compared to the one in the **[media branch](https://github.com/SuperTux/media/blob/master/images/tiles/snow/ice.xcf)** (left), notice almost all detail has been stripped from the tile making it look out of place,

image

- The tile is named "grumbel-ice", which is confusing because we don't name art by contributors,

- The tile isn't referenced anywhere in tiles.strf meaning it lacks any functionality,

- And to top it all off, we already have the iceslick tiles to do this exact purpose, making this tile very redundant.

**Comment by HybridDog** [comment]
> Someone needs to revert this commit […]

Done: https://github.com/SuperTux/supertux/commit/3b2782343c82371f2f9225e1462563eb1b4b55f6

**Comment by Alzter** [comment]
Thanks :)

**Pull request closed without merging**
