### PR TITLE
Add "Editor Guides" button to level editor menu

### PR DESCRIPTION
**Pull request by Vankata453**
Adds a button that redirects the user to the community-made level editor [guides](https://github.com/SuperTux/supertux/wiki/Level-Editor), located in the wiki. The button is positioned on the bottom of the menu. The browser redirection code for the donation button was used.

Aims to provide a temporary solution for #505.

### CODE REVIEW

**Comment by mrkubax10** [comment]
It seems like you are missing `#include <emscripten.h>` and `#include <esmcripten/html5.h>`

**Comment by Semphriss** [comment]
How complete and ready are those guides? Is it a good idea to redirect to GitHub rather than the main site?

Also, the button doesn't look like it opens a browser window. Opening a browser window unexpectedly is poor UX; there should at least be a confirmation dialogue in the user would like to open an external link.

I recommend we discuss all this in discussions before continuing this PR.

**Comment by Vankata453** [comment]
Thanks for the response!

**Comment by Vankata453** [comment]
Will be closing this PR, because of two reasons:

1. As @Semphriss pointed out, those current guides may not really be complete and ready and most of them are made for an older SuperTux version.
2. As mentioned in discussion #2075, made for this PR, it's clear that a new editor guide is developed, which is going to be up-to-date with the newest SuperTux versions and is more likely to be regularly updated and built upon. When this new official level editor guide is released, the addition of an "Editor Guides" button may be rethought.

**Pull request closed without merging**
