### PR TITLE
Fix issue when snail is changing direction

### PR DESCRIPTION
**Pull request by mrkubax10**

### CODE REVIEW

**Comment by Semphriss** [comment]
What was the issue?

**Comment by mrkubax10** [comment]
https://media.discordapp.net/attachments/396022213100437504/894182075278696448/2021-10-03_13-19-53.mp4

**Comment by tobbi** [comment]
Just curious how this happened: Did you not do a normal git revert?

**Comment by mrkubax10** [comment]
I did this manually. I wasn't aware of this command

**Pull request merged**
