### PR TITLE
New menu layout

### PR DESCRIPTION
**Pull request by mahboi**
The new menu code I wrote. Feel free to modify this or rewrite it if you feel it necessary.

### CODE REVIEW

**Comment by Hume2** [comment]
It would be nice for you if I could tell you that I like it...
I guess, you've already read my feedback on bug tracker.

**Comment by mahboi** [comment]
+Hume2 was that sarcasm?

**Comment by Narre** [comment]
What? Yes, it makes some sense, because Contrib levels are game too, but Forest island should be only accessible after finishing IcyIsland and this idea means more menus and it's really annoying. I agree "Start game" and "Contrib levels" are not the best titles, maybe it would be better "Story" and "Contrib levels", but not this.

**Comment by sydneyjd** [comment]
@mahboi Can you get us a couple screenshots of what the start screen looks like in this pull request? I am compiling a vote on what our start screen should look like. Thanks.

**Comment by MarkkusCraft123** [comment]
He's having trouble with his computer, Windows just wiped his grub. But his Debian Jessie is still there.

**Comment by mahboi** [comment]
Finally got Linux back on my laptop (Gentoo is fun on low end computers) after some issues with Windows 10. I should get some screenshots soon.

**Comment by mahboi** [comment]
Finally, after quite a long time (school takes up a large portion of my time now), I've gotten the screenshots.

**Main Menu:**
supertux_1
**Other menu (I've yet to think up a good name):**
supertux_2

**Comment by MarkkusCraft123** [comment]
Looking good!

**Comment by mahboi** [comment]
I don't think anybody cares about this anymore, so I'll try to close it (or get somebody to)

**Comment by sydneyjd** [comment]
Please don' close it till we are sure that we are not going to use it. :)

**Comment by tobbi** [comment]
1 person to be exact. Me.

**Comment by sydneyjd** [comment]
@tobbi ... Add one more... Me. ;) I help with choices also you know. :page_facing_up: 

But really Tobbi, what do you think of this?

**Comment by sydneyjd** [comment]
@mahboi Can you update/rebase this pull request so its up to date with Supertux/master?

**Comment by Hume2** [comment]
In fact, there is a lot of SuperTux developers, but the most of them don't contribute anymore. I'm a SuperTux developer too, at least I'm still an admin on Mantis. I don't remember who has given me that, but it was together with LMH and Ctdabomb. LMH invited more developers and they more, so I don't care about who all is a SuperTux developer.

**Comment by tobbi** [comment]
I'd suggest a vote on the forum about this. I am uncertain which of the two menus is better.

**Comment by Karkus476** [comment]
My vote is going to @mahboi 's menu. I definitely think we should move the Ghost Forest out of contrib and into campaign.

**Comment by sydneyjd** [comment]
@Karkus476 Please post your vote in #108. Thanks.

**Comment by mahboi** [comment]
Sorry about trying to close it. I'm personally tired of messing with this.

**Comment by brmbrmcar** [comment]
This should be implemented if voted for.

**Comment by Savsish** [comment]
I vote for.

**Comment by brmbrmcar** [comment]
@Savsish Go onto the issue page, or your vote may not be counted.

**Comment by MarkkusCraft123** [comment]
Yay!

**Pull request merged**
