### PR TITLE
Compensate for the buffering of frames when vsync is on

### LINKED ISSUE #1117: Camera is jittery
**SuperTux version: master branch**
**System information:** *Windows 10*

##### Expected behavior
Camera moves smoothly when walking

##### Actual behavior
Camera (and Tux) jitters when walking

### PR DESCRIPTION
**Pull request by HybridDog**
This could fix #1117.
@Alzter and others: please test it

### CODE REVIEW

**Comment by Alzter** [comment]
I can't compile stuff.

**Comment by tobbi** [comment]
@Alzter Download this: https://ci.appveyor.com/project/supertux/supertux-o8t59/builds/25202144/artifacts

**Comment by tobbi** [comment]
```
src/supertux/screen_manager.cpp.o -c /home/travis/build/SuperTux/supertux/src/supertux/screen_manager.cpp
/home/travis/build/SuperTux/supertux/src/supertux/screen_manager.cpp: In member function ‘void ScreenManager::run()’:
/home/travis/build/SuperTux/supertux/src/supertux/screen_manager.cpp:470:25: error: conversion from ‘Uint32’ {aka ‘unsigned int’} to ‘float’ may change value [-Werror=conversion]
     elapsed_ms += ticks - last_ticks;
```

**Comment by HybridDog** [comment]
I somehow do not get the warning/error messages even though I enabked the WARNINGS flag (I cleaned the build folder, executed `cmake .. -DWARNINGS=1` and then make).

**Comment by tobbi** [comment]
Which compiler are you working with?

**Comment by HybridDog** [comment]
I use clang because I think that it compiles faster.

**Comment by Alzter** [comment]
This just makes the game feel broken. Now not only does the game randomly slow down, it randomly speeds up too.

**Comment by HybridDog** [comment]
Adaptive vsync does not work for me, so I couldn't test it.
I don't know very much about graphics rendering so I'm not sure if I can help you.
It is possible to use a fixed framerate; this has been done before and avoided the collision bugs, but then frames are occasionally skipped and the keyboard input is read at the same time steps.

**Pull request merged**
