### PR TITLE
Background Rearrangement

### PR DESCRIPTION
**Pull request by serano01**
This would be the first step to rearrange the background folder, like it happened with the music earlier. Would need symlink or the complete rework of all levels, since the game would no longer be able to find the backgrounds.

### CODE REVIEW

**Comment by tobbi** [comment]
Needs something like this: https://github.com/SuperTux/supertux/pull/1191/files

**Comment by serano01** [comment]
@HybridDog: Since you made the other PR regarding the music, are you willing to help with this issue?

**Comment by HybridDog** [comment]
> […] are you willing to help with this issue?

Yes, I can try to help.
To get a list of fallback paths, a commit where the files are moved can be helpful. The current `Background Rearrangement` commit only adds new files (duplicates) and does not (re)move the current files.

**Comment by HybridDog** [comment]
> […] are you willing to help with this issue?

Yes, I can try to help.
To get a list of fallback paths, I changed the commit so that the files are moved and not only duplicates added. 
Then `git diff --raw HEAD~1` shows a list of the moved files. `sed` with the regular expressions just removes the unwanted text.
`git diff --raw @~1 | sed 's:.*R100\t::; s:data/images/background/::g; s:\t:, :g'`
```
arctis2.png, antarctic/arctis2.png
misty_snowhills_small.png, antarctic/misty_snowhills_small.png
semi_arctic.jpg, antarctic/semi_arctic.jpg
bridgecloud-dark.png, arctic_bridge/bridgecloud-dark.png
bridgecloud-light.png, arctic_bridge/bridgecloud-light.png
bridgeocean-fade.png, arctic_bridge/bridgeocean-fade.png
bridgeocean-nofade.png, arctic_bridge/bridgeocean-nofade.png
bridgeocean-original.png, arctic_bridge/bridgeocean-original.png
arcticskies1.png, arcticskies/arcticskies1.png
arcticskies2.png, arcticskies/arcticskies2.png
arcticskies3.png, arcticskies/arcticskies3.png
arcticskies35.png, arcticskies/arcticskies35.png
arcticskies4.png, arcticskies/arcticskies4.png
block-snow-background.png, block_snow/block-snow-background.png
block-snow-midground.png, block_snow/block-snow-midground.png
block-snow-top.png, block_snow/block-snow-top.png
bluemountain-bottom.png, bluemountain/bluemountain-bottom.png
bluemountain-middle.png, bluemountain/bluemountain-middle.png
bluemountain-top.png, bluemountain/bluemountain-top.png
bluemountain2.png, bluemountain/bluemountain2.png
castle_foreground.png, castle/castle_foreground.png
snowcastle.png, castle/snowcastle.png
cloud-mountains-background.png, cloud_mountains/cloud-mountains-background.png
cloud-mountains-bottom.png, cloud_mountains/cloud-mountains-bottom.png
cloud-mountains-forground.png, cloud_mountains/cloud-mountains-forground.png
cloud-mountains-midground.png, cloud_mountains/cloud-mountains-midground.png
dawn_hill_para_blur.png, forest/dawn_hill_para_blur.png
forest2_para.png, forest/forest2_para.png
forest_para2.png, forest/forest_para2.png
forest_para3.png, forest/forest_para3.png
forest_para3_bottom.png, forest/forest_para3_bottom.png
nighthills.png, forest/nighthills.png
ghostforest.jpg, ghostforest/ghostforest.jpg
ghostforest_grave.png, ghostforest/ghostforest_grave.png
ghostforest_para.png, ghostforest/ghostforest_para.png
cave2.jpg, ice_cave/cave2.jpg
darkcave-background.png, ice_cave/darkcave-background.png
darkcave-middle.png, ice_cave/darkcave-middle.png
darkcave-preview.png, ice_cave/darkcave-preview.png
darkcave-top_and_bottom.png, ice_cave/darkcave-top_and_bottom.png
darkcavemidground-middle.png, ice_cave/darkcavemidground-middle.png
darkcavemidground-top_and_bottom.png, ice_cave/darkcavemidground-top_and_bottom.png
black_800px.png, misc/black_800px.png
fog.png, misc/fog.png
grid.png, misc/grid.png
grid.surface, misc/grid.surface
heatshimmer-displacement.png, misc/heatshimmer-displacement.png
heatshimmer.png, misc/heatshimmer.png
heatshimmer.surface, misc/heatshimmer.surface
leaves.png, misc/leaves.png
oiltux.jpg, misc/oiltux.jpg
transparent_up.png, misc/transparent_up.png
nightsky.png, nightsky/nightsky.png
nightsky_bottom.png, nightsky/nightsky_bottom.png
nightsky_middle.png, nightsky/nightsky_middle.png
nightsky_para.png, nightsky/nightsky_para.png
nightsky_top.png, nightsky/nightsky_top.png
```

**Comment by serano01** [comment]
@HybridDog Dude, you're cool. Thanks a lot.

**Comment by serano01** [comment]
I've tested it, the game is not able to find all backgrounds, like arctis2.jpg (the default background when creating a new level).

**Comment by HybridDog** [comment]
>I've tested it, the game is not able to find all backgrounds

>it does not yet search for the fallback.

**Comment by serano01** [comment]
Oh sorry, I've missed that.

**Comment by HybridDog** [comment]
I've implemented it now and changed some other code.

I didn't change the TextScrollerScreen because I don't know what it does,
and I did not fix the old sector parser background loading.

Some images have arctic in their name, e.g. arctis2.png, although penguins live in the antarctis. I don't know if this needs to be fixed.

**Pull request merged**
