### PR TITLE
Buttjump hitbox adjusted to reflect sprite

### PR DESCRIPTION
**Pull request by Zwatotem**
Now Tux's hitbox gets squished to the center of his body while performing pre-buttjump animation. That means he can jump higher/further and avoid collisions from above (e.g. from ice spikes).
Before:
before
After:
after

### CODE REVIEW

**Comment by tobbi** [comment]
@Rusty-Box @serano01 @weluvgoatz @Alzter You guys approve?

**Comment by weluvgoatz** [comment]
I will test later.

**Comment by weluvgoatz** [comment]
The buttjump hitbox is broken and Tux digs into the ground when he buttjumps.

**Comment by Zwatotem** [comment]
Okay, to be fair, I also adjusted the sprite to follow intuition, e.i. to squize to the center of his body instead of lower part. And then I addjusted the intuition :-) , so that Tux can easly get one full tile higher (jump on gifs was a criterium). So in the end Tux' hitbox shirnks about 15px from the bottom, and like 2px from the top.
Maybe I should change it to more symmetric? Let me know.

> The buttjump hitbox is broken and Tux digs into the ground when he buttjumps.

Don't forget, that on Windows sprites are not reloaded on installation. For me it's fine.

**Comment by HybridDog** [comment]
If I understand it correctly, this can break a lots of existing levels because Tux can jump to places which he should not be able to reach.

**Comment by Alzter** [comment]
Kinda looks like he's clipping through the floor and could break existing levels as @HybridDog said, maybe not...?

**Comment by Zwatotem** [comment]
I have no time to adjust it further now, I'll take care of it later. @Alzter feel free to test for yourself.
I don't think it's gonna do that much of a difference, since if somebody is grown, he's gonna reach the same height already. Although I consider redoing it since it's primary goal was to shrink collision from above, not from below.

**Comment by Zwatotem** [comment]
This has been getting no interest over last few months, closing.

**Pull request closed without merging**
