### PR TITLE
Mr. Iceblock falls off any ledge

### PR DESCRIPTION
**Pull request by MatusGuy**
I wanted to leave this up to discussion so i made a pull request instead of committing directly.

### CODE REVIEW

**Comment by tobbi** [comment]
🇱🇹 🐔

**Comment by Vankata453** [comment]
I think this would make sense, since the smartblock exists so it doesn't fall of ledges.

**Comment by mrkubax10** [comment]
Yeah, me too.

**Comment by CentrawhileYT** [comment]
Well, I'd prefer the AI where the iceblock falls off ledges safe to land on, similar to the spiky's AI.

**Pull request merged**
