### PR TITLE
[WIP] Update wasm.yml (PR to your PR)

### PR DESCRIPTION
**Pull request by Pospelove**
just wanted to test a workflow

related https://github.com/microsoft/vcpkg/issues/29574

### CODE REVIEW

**Comment by tobbi** [comment]
```
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

CMake Error: The source directory "/home/runner/work/supertux/supertux/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

**Comment by tobbi** [comment]
Our CMakeLists.txt file is in the root directory, but we create the build output in the `build` subdirectory.

**Comment by tobbi** [comment]
Workflow approved again.

**Comment by tobbi** [comment]
```
CMake Error at /usr/local/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR filesystem system
  date_time locale)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.25/Modules/FindBoost.cmake:2377 (find_package_handle_standard_args)
  mk/cmake/SuperTux/ProvideBoost.cmake:15 (find_package)
  CMakeLists.txt:155 (include)


-- Configuring incomplete, errors occurred!
See also "/home/runner/work/supertux/supertux/build/CMakeFiles/CMakeOutput.log".
See also "/home/runner/work/supertux/supertux/build/CMakeFiles/CMakeError.log".
emcmake: error: 'cmake .. -DCMAKE_BUILD_TYPE=Debug -DENABLE_OPENGLES2=ON -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/runner/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_TOOLCHAIN_FILE=/home/runner/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/home/runner/emsdk/node/14.18.2_64bit/bin/node;--experimental-wasm-bulk-memory;--experimental-wasm-threads' failed (returned 1)
```

**Comment by Pospelove** [comment]
@tobbi  removed emcmake. this command overwrites CMAKE_TOOLCHAIN_FILE. then no libraries are found

**Comment by tobbi** [comment]
Seemed to still fail with the same error message
```
CMake Error at /usr/local/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR filesystem system
  date_time locale)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
-- Configuring incomplete, errors occurred!
  /usr/local/share/cmake-3.25/Modules/FindBoost.cmake:2377 (find_package_handle_standard_args)
See also "/home/runner/work/supertux/supertux/build/CMakeFiles/CMakeOutput.log".
  mk/cmake/SuperTux/ProvideBoost.cmake:15 (find_package)
See also "/home/runner/work/supertux/supertux/build/CMakeFiles/CMakeError.log".
  CMakeLists.txt:155 (include)
```

**Comment by Pospelove** [comment]
well trying to use Boost::boost target

**Comment by tobbi** [comment]
Same error, it seems.

**Comment by Pospelove** [comment]
yeah no problem thats ok
I see error but bored a bit fixing it lol
I wanted to prove that boost-fs:wasm32-emscripten links so we should close vcpkg issue

but mehh it's compilcated

Im doing basically the same as I do in my blank project and for me it works :(

**Comment by tobbi** [comment]
Can you rebase this maybe, so I can merge?

**Comment by Pospelove** [comment]
@tobbi +

**Pull request merged**
