### PR TITLE
Update PhysFS to 3.2.0

### PR DESCRIPTION
**Pull request by tobbi**
We have been on some rather old-ish version of PhysFS since quite a while. Even though we support building against locally installed versions of PhysFS; I feel like updating to the latest release version can have benefits.

### CODE REVIEW

**Comment by tobbi** [comment]
I think we should update the submodule reference to point to upstream PhysFS. All the changes that were on the supertux-changes branch on our local fork of the submodule have already been incorporated upstream.

We should keep the repository archived, so existing builds don't start failing. 

Unfortunately, the history of our "fork" is not compatible with the upstream here: github.com/icculus/physfs because one was created using some hg-to-git

**Comment by tobbi** [comment]
Maybe I'll rename the branch name on our fork so that we can have the same branches as upstream does.

**Review by MatusGuy — APPROVED** [review]
Tested. Works on ubuntu jammy

**Review by mrkubax10 — APPROVED** [review]

**Review by Vankata453 — APPROVED** [review]
> I think we should update the submodule reference to point to upstream PhysFS.

Yeah, would be good, since with this PR, we are using an upstream release either way.

Otherwise, this builds fine on Arch Linux and runs properly.

**Comment by tobbi** [comment]
Can I make our physfs clone read-only?

**Comment by Vankata453** [comment]
> Can I make our physfs clone read-only?

Sure.

**Comment by tobbi** [comment]
I've archived our clone now and added a note stating the reasons for the deprecation.

**Comment by tobbi** [comment]
I'm rerunning this one mac build and will merge tomorrow.

**Comment by tobbi** [comment]
Since I can't sleep, I might as well merge now.

**Pull request merged**
