### PR TITLE
WIP: Maybe fix physfs path

### PR DESCRIPTION
**Pull request by tobbi**
Okay, so obviously this does not work...Or maybe not so obviously...

I tried adding the physfs paths of add-ons to a list...
And I'm basically, then mounting them when the list of contrib levels get loaded...So far so good...

The only problem is that the loading of the completed levels from the physfs shares does not seem to be working...as all the contrib levels are marked as new...So, squirrel does not load the state table properly. Why? The hell do I know...

If someone who knows about these things could take a look, that would be much appreciated.

### CODE REVIEW

**Comment by tobbi** [comment]
@Grumbel Sorry for pinging you, but I might need your help.

I'm trying to defer mounting add-on zip paths until they're actually needed...e.g. when the Contrib levels menu is loaded or the worlds specified in that add-on are loaded for sure. 

I thought that the approach I chose here (add paths to load to a map, then load them on demand) but for some reason this messes with how Squirrel loads the level state...And I have no idea why. Could you please take a look?

**Comment by tobbi** [comment]
I've investigated some more: For some reason, Squirrel can't find the "levels" table entry, despite it being created a couple calls earlier.

**Comment by plonibarploni** [comment]
> The only problem is that the loading of the completed levels from the physfs shares does not seem to be working...as all the contrib levels are marked as new...So, squirrel does not load the state table properly. Why? The hell do I know...

Is this possibly related to #1251?

> I've investigated some more: For some reason, Squirrel can't find the "levels" table entry, despite it being created a couple calls earlier.

That would probably explain why this code is never executed, causing the levels be marked as new:
https://github.com/SuperTux/supertux/blob/a0cd2f4e6512ca12b0ab813fbc827ba62e1cbad3/src/supertux/menu/contrib_menu.cpp#L134-L144

Is it possible that the state is now saved differently? Older versions can't read the level state from newer versions either (I get inconsistent results, sometimes it says "new" and sometimes "0/22").

**Comment by tobbi** [comment]
> > The only problem is that the loading of the completed levels from the physfs shares does not seem to be working...as all the contrib levels are marked as new...So, squirrel does not load the state table properly. Why? The hell do I know...
> 
> Is this possibly related to #1251?

I don't think so. This is an issue that got introduced through my changes...

> > I've investigated some more: For some reason, Squirrel can't find the "levels" table entry, despite it being created a couple calls earlier.
> 
> That would probably explain why this code is never executed, causing the levels be marked as new:
> 
> https://github.com/SuperTux/supertux/blob/a0cd2f4e6512ca12b0ab813fbc827ba62e1cbad3/src/supertux/menu/contrib_menu.cpp#L134-L144
> 
> Is it possible that the state is now saved differently? Older versions can't read the level state from newer versions either (I get inconsistent results, sometimes it says "new" and sometimes "0/22").

If only I knew...

**Comment by tobbi** [comment]
@martinvanzijl @Zwatotem I know this is a long shot, and I also think you might not know enough about physfs to help with this (I think I already mentioned this to you, @Zwatotem). If anyone of you can find out what's wrong with this, I'd be very grateful. This is *the* issue preventing us from getting a new release.

**Comment by martinvanzijl** [comment]
@tobbi I'm not familiar with physfs but I could take a look. What are the steps to reproduce the issue?

**Comment by tobbi** [comment]
Install Slackstone's add-on from here:
https://raw.githubusercontent.com/SuperTux/addons/master/repository/forest_world_adventure_pack.zip

(copy it into the add-ons directory)...see how the assets from the add-on override the assets from the game. Due to physfs overriding.

**Comment by tobbi** [comment]
Some further comments: If you take a look at https://github.com/SuperTux/supertux/pull/1364/files#diff-bfcd1496905218f4e56f865be1828669R358 I'm outputting all the table entries.

It produces the following output:
```
[WARNING] supertux/src/supertux/savegame.cpp:359 /levels/revenge_in_redmond/worldmap.stwm
[WARNING] supertux/src/supertux/savegame.cpp:373 Squirrel error: failed to get 'levels/revenge_in_redmond/worldmap.stwm' table entry (the index 'levels/revenge_in_redmond/worldmap.stwm' does not exist)
```

Obviously, you might be thinking "Ah, that's easy, simply add a forward slash to the search path in savegame.cpp, line 363. I tried that, to no avail.

**Comment by martinvanzijl** [comment]
Thanks. After installing the add-on, when I restart SuperTux the opening screen is different and there is no music. Also some sprites are different in the levels (such as bonus blocks). Are these the things being overridden?

**Comment by tobbi** [comment]
> Thanks. After installing the add-on, when I restart SuperTux the opening screen is different and there is no music. Also some sprites are different in the levels (such as bonus blocks). Are these the things being overridden?

Exactly!

**Comment by martinvanzijl** [comment]
Ah, I see. And with this patch applied, the main screen and levels are now normal again, but I cannot see any levels listed for the add-on.

**Comment by tobbi** [comment]
The add-on paths are loaded when the add-ons menu is loaded. But for some reason, it won't work then...It's supposed to load the add-on zips to figure out how many levels there are. But it won't display the level count.

**Comment by martinvanzijl** [comment]
Ah, I see. It should put the figures for levels completed/total in the menu here:

level-info-screenshot

But instead it just says "\*NEW\*". And this is because it cannot read the key which has this information, in `savegame.cpp` with this line:

```
vm.get_or_create_table_entry(name);
```

**Comment by tobbi** [comment]
> Ah, I see. It should put the figures for levels completed/total in the menu here:
> 
> level-info-screenshot
> 
> But instead it just says "*NEW*". And this is because it cannot read the key which has this information, in `savegame.cpp` with this line:
> 
> ```
> vm.get_or_create_table_entry(name);
> ```

You got it! :)

**Comment by martinvanzijl** [comment]
OK, I think I made some progress. If I comment out the lines which list the keys (358 and 359), it seems to read the key on line 361 OK. At least, it does not throw an exception. Like so:

```
    //for(const auto& key : vm.get_table_keys())
      //log_warning << "Existing key: " << key << std::endl;

    vm.get_or_create_table_entry(name);
```

It seems `SquirrelVM::get_table_keys()` does some stack manipulation, which may cause the key to be missed on line 361.

However, then it still cannot find the "levels" sub-key on line 365.

**Comment by tobbi** [comment]
Okay, hold on, let me see if I can fix that.

**Comment by tobbi** [comment]
@martinvanzijl Thank you, I've fixed it by restoring the old stack's top. Now it even displays the level info...Next up: Loading the physfs path when loading the levelset... (currently, levelsets are empty).

**Comment by tobbi** [comment]
For loading the zip file when loading the world, I'm hitting some kind of roadblock: When a level has been edited, it gets saved outside the zip file...When I'm now querying for the level's basedir, the location outside that zip file gets returned. I'm not sure how to fix that best without constantly unmounting / mounting that extra directory.

**Comment by tobbi** [comment]
@christ2go suggested a way easier method. Because of this, I'm closing it.

**Pull request closed without merging**
