### PR TITLE
Appdata updates

### PR DESCRIPTION
**Pull request by reinerh**
- screenshots need to be placed in either `<image>` or `<video>` tags to be compliant
- update homepage
- drop outdated mailinglist address
- add additional urls

see also: https://freedesktop.org/software/appstream/docs/chap-Metadata.html

### CODE REVIEW

**Comment by Laksh61isback** [comment]
o

**Comment by Laksh61isback** [comment]
m

**Comment by Laksh61isback** [comment]
g

**Comment by Laksh61isback** [comment]
fell

**Review by mrkubax10 — APPROVED** [review]

**Review by Zwatotem — APPROVED** [review]

**Pull request merged**
