### PR TITLE
Ghostwood tiles overhaul

### PR DESCRIPTION
**Pull request by Hume2**
Fixing bug #112 .

### CODE REVIEW

**Comment by maxteufel** [comment]
Can you put the `[ci skip]` in the third line of the commit message so it's less annoying when reading the log?

**Comment by maxteufel** [comment]
Also, if you add `Fixes #112` (oslt) to the commit message, GitHub will auto-close the issue. (See <https://help.github.com/articles/closing-issues-via-commit-messages/>).

I propose a commit message like this:

```
Ghostwood tiles overhaul (fixes #112)

[ci skip]
```

**Comment by maxteufel** [comment]
LGTM, but looks like it'll break add-on compatibility.

**Comment by Hume2** [comment]
Which levels, exactly?

**Comment by maxteufel** [comment]
Well, why did you change the `ghostly.stl` then? (Sorry, github doesn't diff them because it thinks it's a 3D-model)

**Comment by Hume2** [comment]
I changed it because it was broken.
And is there any other level, that it broke? I don't know any, because these tiles seemed too ugly, so noone used them.

**Comment by maxteufel** [comment]
No I don't know/remember any others using these tiles.

Oh well, and if something breaks, add-on maintainers are responsible for fixing it anyway.

**Pull request merged**
